
import { PlatformData } from './types';

export const platforms: PlatformData[] = [
  {
    id: 'google-ads',
    name: 'Google Ads',
    description: 'The world\'s largest advertising network reaching users across Search, YouTube, Discovery, and millions of websites.',
    lastUpdated: '2025-10-28',
    specs: [
      // Performance Max
      {
        id: 'gads-pmax-land',
        title: 'Performance Max (Landscape)',
        dimensions: '1200×628',
        width: 1200,
        height: 628,
        aspectRatio: '1.91:1',
        format: 'Image',
        fileType: ['JPG', 'PNG'],
        maxFileSize: '5MB',
        maxFileSizeBytes: 5 * 1024 * 1024,
        notes: 'Min size: 600×314. Max file size: 5120 KB.'
      },
      {
        id: 'gads-pmax-land-vid',
        title: 'Performance Max (Landscape)',
        dimensions: '1200×628',
        width: 1200,
        height: 628,
        aspectRatio: '1.91:1',
        format: 'Video',
        fileType: ['MPG', 'MOV'],
        maxFileSize: 'N/A',
        notes: 'Recommended length: 10-60 seconds, 1-20 videos (recommended: 3).'
      },
      {
        id: 'gads-pmax-sq',
        title: 'Performance Max (Square)',
        dimensions: '1200×1200',
        width: 1200,
        height: 1200,
        aspectRatio: '1:1',
        format: 'Image',
        fileType: ['JPG', 'PNG'],
        maxFileSize: '5MB',
        maxFileSizeBytes: 5 * 1024 * 1024,
        notes: 'Min size: 300×300. Max file size: 5120 KB.'
      },
      {
        id: 'gads-pmax-sq-vid',
        title: 'Performance Max (Square)',
        dimensions: '1200×1200',
        width: 1200,
        height: 1200,
        aspectRatio: '1:1',
        format: 'Video',
        fileType: ['MPG', 'MOV'],
        maxFileSize: 'N/A',
        notes: 'Recommended length: 10-60 seconds, 1-20 videos (recommended: 2).'
      },
      {
        id: 'gads-pmax-port',
        title: 'Performance Max (Portrait)',
        dimensions: '960×1200',
        width: 960,
        height: 1200,
        aspectRatio: '4:5',
        format: 'Image',
        fileType: ['JPG', 'PNG'],
        maxFileSize: '5MB',
        maxFileSizeBytes: 5 * 1024 * 1024,
        notes: '(min 480 × 600 pixels)'
      },
      {
        id: 'gads-pmax-port-vid',
        title: 'Performance Max (Portrait)',
        dimensions: '960×1200',
        width: 960,
        height: 1200,
        aspectRatio: '4:5',
        format: 'Video',
        fileType: ['MPG', 'MOV'],
        maxFileSize: 'N/A',
        notes: 'Recommended length: 10-60 seconds, 1-20 videos (recommended: 7).'
      },
      {
        id: 'gads-pmax-story',
        title: 'Performance Max (Story)',
        dimensions: '1080×1920',
        width: 1080,
        height: 1920,
        aspectRatio: '9:16',
        format: 'Image',
        fileType: ['JPG', 'PNG'],
        maxFileSize: '5MB',
        maxFileSizeBytes: 5 * 1024 * 1024,
        notes: '(min 600×1067 pixels)'
      },
      {
        id: 'gads-pmax-story-vid',
        title: 'Performance Max (Story)',
        dimensions: '1080×1920',
        width: 1080,
        height: 1920,
        aspectRatio: '9:16',
        format: 'Video',
        fileType: ['MPG', 'MOV'],
        maxFileSize: 'N/A',
        notes: 'Recommended length: 10-60 seconds, 1-5 videos.'
      },

      // App Campaigns
      {
        id: 'gads-app-sq',
        title: 'App Campaign (Square)',
        dimensions: '1200×1200',
        width: 1200,
        height: 1200,
        aspectRatio: '1:1',
        format: 'Image',
        fileType: ['JPG', 'PNG'],
        maxFileSize: '5MB',
        maxFileSizeBytes: 5 * 1024 * 1024,
        notes: 'Minimum size: 600×600 px. Max file size: 5120 KB.'
      },
      {
        id: 'gads-app-land',
        title: 'App Campaign (Landscape)',
        dimensions: '1200×628',
        width: 1200,
        height: 628,
        aspectRatio: '1.91:1',
        format: 'Image',
        fileType: ['JPG', 'PNG'],
        maxFileSize: '5MB',
        maxFileSizeBytes: 5 * 1024 * 1024,
        notes: 'Minimum size: 600×314 px. Max file size: 5120 KB.'
      },
      {
        id: 'gads-app-vid',
        title: 'App Campaign (Video)',
        dimensions: '1920×1080',
        width: 1920,
        height: 1080,
        aspectRatio: '16:9',
        format: 'Video',
        fileType: ['MP4', 'MOV'],
        maxFileSize: 'N/A',
        settings: 'H.264 or H.265 compression, square pixels, fixed frame rate (30fps recommended), progressive scan and stereo AAC audio compression at 128kbps+. First 5 seconds should capture attention.',
        notes: 'Recommended length: 30 seconds or less. Landscape (16:9) or square (1:1) format.'
      },

      // Display Campaigns
      {
        id: 'gads-display-sq',
        title: 'Display Campaign (Square)',
        dimensions: '1200×1200',
        width: 1200,
        height: 1200,
        aspectRatio: '1:1',
        format: 'Image',
        fileType: ['JPG', 'PNG'],
        maxFileSize: '5MB',
        maxFileSizeBytes: 5 * 1024 * 1024,
        notes: 'Minimum size: 300×300 px. Max file size: 5120 KB.'
      },
      {
        id: 'gads-display-land',
        title: 'Display Campaign (Landscape)',
        dimensions: '1200×628',
        width: 1200,
        height: 628,
        aspectRatio: '1.91:1',
        format: 'Image',
        fileType: ['JPG', 'PNG'],
        maxFileSize: '5MB',
        maxFileSizeBytes: 5 * 1024 * 1024,
        notes: 'Minimum size: 600×314 px. Max file size: 5120 KB.'
      },
      {
        id: 'gads-display-banner',
        title: 'Display Campaign (Banner)',
        dimensions: '300×250',
        width: 300,
        height: 250,
        aspectRatio: '1.2:1',
        format: 'Image',
        fileType: ['JPG', 'PNG', 'GIF'],
        maxFileSize: '150KB',
        maxFileSizeBytes: 150 * 1024,
        notes: 'Medium Rectangle (300×250) is one of the most common display ad sizes.'
      },

      // Demand Gen
      {
        id: 'gads-demand-land',
        title: 'Demand Gen (Landscape)',
        dimensions: '1200×628',
        width: 1200,
        height: 628,
        aspectRatio: '1.91:1',
        format: 'Image',
        fileType: ['JPG', 'PNG'],
        maxFileSize: '5MB',
        maxFileSizeBytes: 5 * 1024 * 1024,
        notes: 'Min size: 600×314. Required for some placements.'
      },
      {
        id: 'gads-demand-sq',
        title: 'Demand Gen (Square)',
        dimensions: '1200×1200',
        width: 1200,
        height: 1200,
        aspectRatio: '1:1',
        format: 'Image',
        fileType: ['JPG', 'PNG'],
        maxFileSize: '5MB',
        maxFileSizeBytes: 5 * 1024 * 1024,
        notes: 'Min size: 300×300.'
      },
      {
        id: 'gads-demand-port',
        title: 'Demand Gen (Portrait)',
        dimensions: '960×1200',
        width: 960,
        height: 1200,
        aspectRatio: '4:5',
        format: 'Image',
        fileType: ['JPG', 'PNG'],
        maxFileSize: '5MB',
        maxFileSizeBytes: 5 * 1024 * 1024,
        notes: 'Min size: 480×600.'
      },
      {
        id: 'gads-demand-logo',
        title: 'Demand Gen (Logo)',
        dimensions: '1200×1200',
        width: 1200,
        height: 1200,
        aspectRatio: '1:1',
        format: 'Image',
        fileType: ['JPG', 'PNG'],
        maxFileSize: '5MB',
        maxFileSizeBytes: 5 * 1024 * 1024,
        notes: 'Min size: 128×128. Recommended for best quality.'
      },

      // Video Campaigns
      {
        id: 'gads-video-instream',
        title: 'Video Campaign - In-stream',
        dimensions: '1920×1080',
        width: 1920,
        height: 1080,
        aspectRatio: '16:9',
        format: 'Video',
        fileType: ['MP4', 'MOV'],
        maxFileSize: 'N/A',
        settings: 'H.264 compression (High Profile recommended), square pixels, fixed frame rate (30fps recommended), progressive scan and stereo AAC audio compression at 128kbps+. 8,000-10,000 kbps bitrate for 1080p.',
        notes: 'Recommended length: 15-30 seconds. Landscape format (16:9) preferred.'
      },
      {
        id: 'gads-video-bumper',
        title: 'Video Campaign - Bumper',
        dimensions: '1920×1080',
        width: 1920,
        height: 1080,
        aspectRatio: '16:9',
        format: 'Video',
        fileType: ['MP4', 'MOV'],
        maxFileSize: 'N/A',
        settings: 'H.264 compression, square pixels, fixed frame rate (30fps recommended), progressive scan and stereo AAC audio compression at 128kbps+.',
        notes: 'Maximum length: 6 seconds. Must be skippable after 6 seconds.'
      },
      {
        id: 'gads-video-outstream',
        title: 'Video Campaign - Outstream',
        dimensions: '1920×1080',
        width: 1920,
        height: 1080,
        aspectRatio: '16:9',
        format: 'Video',
        fileType: ['MP4', 'MOV'],
        maxFileSize: 'N/A',
        settings: 'H.264 compression, square pixels, fixed frame rate (30fps recommended), progressive scan and stereo AAC audio compression at 128kbps+.',
        notes: 'Plays outside of YouTube content. Square (1:1) format works well for mobile. Aspect ratio is 16:9 or 1:1.'
      },

      // Search Campaigns
      {
        id: 'gads-search-sq',
        title: 'Search Campaign (Square)',
        dimensions: '1200×1200',
        width: 1200,
        height: 1200,
        aspectRatio: '1:1',
        format: 'Image',
        fileType: ['JPG', 'PNG'],
        maxFileSize: '5MB',
        maxFileSizeBytes: 5 * 1024 * 1024,
        notes: 'Minimum size: 300×300 px. Used for image extensions in search ads.'
      },
      {
        id: 'gads-search-land',
        title: 'Search Campaign (Landscape)',
        dimensions: '1200×628',
        width: 1200,
        height: 628,
        aspectRatio: '1.91:1',
        format: 'Image',
        fileType: ['JPG', 'PNG'],
        maxFileSize: '5MB',
        maxFileSizeBytes: 5 * 1024 * 1024,
        notes: 'Minimum size: 600×314 px. Used for image extensions in search ads.'
      },
      {
        id: 'gads-search-logo',
        title: 'Search (Business Logo)',
        dimensions: '1200×1200',
        width: 1200,
        height: 1200,
        aspectRatio: '1:1',
        format: 'Image',
        fileType: ['JPG', 'PNG'],
        maxFileSize: '5MB',
        maxFileSizeBytes: 5 * 1024 * 1024,
        notes: 'Recommended. Min size: 128×128.'
      },

      // Standard Display Banners (Retained for completeness)
      {
        id: 'gads-display-leader',
        title: 'Leaderboard',
        dimensions: '728×90',
        width: 728,
        height: 90,
        aspectRatio: '8:1',
        format: 'Image',
        fileType: ['JPG', 'PNG', 'GIF'],
        maxFileSize: '150KB',
        maxFileSizeBytes: 150 * 1024,
        notes: 'Standard top-of-page banner for desktop. Keep key visuals simple due to height constraints.'
      },
      {
        id: 'gads-display-half',
        title: 'Half Page Ad',
        dimensions: '300×600',
        width: 300,
        height: 600,
        aspectRatio: '1:2',
        format: 'Image',
        fileType: ['JPG', 'PNG', 'GIF'],
        maxFileSize: '150KB',
        maxFileSizeBytes: 150 * 1024,
        notes: 'One of the fastest growing sizes. Offers high impact and screen real estate on desktop.'
      },
      {
        id: 'gads-display-mob-large',
        title: 'Large Mobile Banner',
        dimensions: '320×100',
        width: 320,
        height: 100,
        aspectRatio: '3.2:1',
        format: 'Image',
        fileType: ['JPG', 'PNG', 'GIF'],
        maxFileSize: '150KB',
        maxFileSizeBytes: 150 * 1024,
        notes: 'Specific to mobile devices. Often replaces the smaller 320x50 format.'
      },
      {
        id: 'gads-display-sky',
        title: 'Wide Skyscraper',
        dimensions: '160×600',
        width: 160,
        height: 600,
        aspectRatio: '1:3.75',
        format: 'Image',
        fileType: ['JPG', 'PNG', 'GIF'],
        maxFileSize: '150KB',
        maxFileSizeBytes: 150 * 1024,
        notes: 'Sidebar placement for desktop websites.'
      }
    ]
  },
  {
    id: 'instagram',
    name: 'Instagram',
    description: 'Instagram is a dynamic visual platform where users share high-quality photos and engaging short videos (Reels). Ideal for brand showcasing.',
    lastUpdated: '2025-07-14',
    specs: [
      {
        id: 'ig-square',
        title: 'Square Feed Post',
        dimensions: '1440×1440',
        width: 1440,
        height: 1440,
        aspectRatio: '1:1',
        format: 'Image',
        fileType: ['JPG', 'PNG'],
        maxFileSize: '30MB',
        maxFileSizeBytes: 30 * 1024 * 1024,
        notes: 'Ideal for balanced visual content across feeds.'
      },
      {
        id: 'ig-vertical',
        title: 'Vertical Feed Post',
        dimensions: '1080×1350',
        width: 1080,
        height: 1350,
        aspectRatio: '4:5',
        format: 'Image',
        fileType: ['JPG', 'PNG'],
        maxFileSize: '30MB',
        maxFileSizeBytes: 30 * 1024 * 1024,
        notes: 'Optimized for mobile screens; visually dominant on smaller devices.'
      },
      {
        id: 'ig-landscape',
        title: 'Landscape Feed Post',
        dimensions: '1080×566',
        width: 1080,
        height: 566,
        aspectRatio: '1.91:1',
        format: 'Image',
        fileType: ['JPG', 'PNG'],
        maxFileSize: '30MB',
        maxFileSizeBytes: 30 * 1024 * 1024,
        notes: 'Best for horizontal or panoramic visuals.'
      },
      {
        id: 'ig-story',
        title: 'Story Post',
        dimensions: '1440×2560',
        width: 1440,
        height: 2560,
        aspectRatio: '9:16',
        format: 'Image',
        fileType: ['JPG', 'PNG'],
        maxFileSize: '30MB',
        maxFileSizeBytes: 30 * 1024 * 1024,
        notes: 'Keep design elements 250px from top, 340px bottom to avoid being obscured by UI.'
      },
      {
        id: 'ig-story-video',
        title: 'Story Post (Video)',
        dimensions: '1440×2560',
        width: 1440,
        height: 2560,
        aspectRatio: '9:16',
        format: 'Video',
        fileType: ['MP4', 'MOV', 'GIF'],
        maxFileSize: '4GB',
        maxFileSizeBytes: 4 * 1024 * 1024 * 1024,
        settings: 'H.264 compression, fixed frame rate, stereo AAC audio at 128kbps+.',
        notes: 'Keep design elements 250px from top, 340px bottom to avoid being obscured by UI.'
      },
      {
        id: 'ig-reels',
        title: 'Reels',
        dimensions: '1440×2560',
        width: 1440,
        height: 2560,
        aspectRatio: '9:16',
        format: 'Video',
        fileType: ['MP4', 'MOV', 'GIF'],
        maxFileSize: '4GB',
        maxFileSizeBytes: 4 * 1024 * 1024 * 1024,
        settings: 'H.264 compression, fixed frame rate, stereo AAC audio at 128kbps+.',
        notes: 'Cover image should be same size. Reels appear as 1:1 in profile feed, 4:5 in home feed. Keep key elements centered.'
      },
      {
        id: 'ig-shopping-img',
        title: 'Shopping Ad',
        dimensions: '1080×1080',
        width: 1080,
        height: 1080,
        aspectRatio: '1:1',
        format: 'Image',
        fileType: ['JPG', 'PNG'],
        maxFileSize: '30MB',
        maxFileSizeBytes: 30 * 1024 * 1024,
        notes: 'Product ads with shopping tags. Similar to single image ads but with product tagging capability. Aspect ratio is 1:1 or 4:5.'
      },
      {
        id: 'ig-shopping-video',
        title: 'Shopping Ad',
        dimensions: '1080×1350',
        width: 1080,
        height: 1350,
        aspectRatio: '4:5',
        format: 'Video',
        fileType: ['MP4', 'MOV', 'GIF'],
        maxFileSize: '4GB',
        maxFileSizeBytes: 4 * 1024 * 1024 * 1024,
        settings: 'H.264 compression, square pixels, fixed frame rate, progressive scan and stereo AAC audio compression at 128kbps+.',
        notes: 'Video shopping ads with product tags. Showcase products in action. Aspect ratio is 4:5 or 1:1.'
      },
      {
        id: 'ig-feed-ad-sq-img',
        title: 'Feed Ad (Square)',
        dimensions: '1440×1440',
        width: 1440,
        height: 1440,
        aspectRatio: '1:1',
        format: 'Image',
        fileType: ['JPG', 'PNG'],
        maxFileSize: '30MB',
        maxFileSizeBytes: 30 * 1024 * 1024,
        notes: 'Avoid heavy text, as Instagram prioritizes clean and visually appealing ads. Supports square, landscape and vertical. Aspect ratio is 1:1 or 1.91:1.'
      },
      {
        id: 'ig-feed-ad-sq-video',
        title: 'Feed Ad (Square)',
        dimensions: '1440×1440',
        width: 1440,
        height: 1440,
        aspectRatio: '1:1',
        format: 'Video',
        fileType: ['MP4', 'MOV', 'GIF'],
        maxFileSize: '4GB',
        maxFileSizeBytes: 4 * 1024 * 1024 * 1024,
        settings: 'H.264 compression, square pixels, fixed frame rate, progressive scan and stereo AAC audio compression at 128kbps+.',
        notes: 'Stick to minimal text for improved performance. Ratio: 1:1 (for desktop or mobile) or 4:5 (for mobile only).'
      },
      {
        id: 'ig-story-ad-img',
        title: 'Story Ad (Vertical)',
        dimensions: '1440×2560',
        width: 1440,
        height: 2560,
        aspectRatio: '9:16',
        format: 'Image',
        fileType: ['JPG', 'PNG'],
        maxFileSize: '30MB',
        maxFileSizeBytes: 30 * 1024 * 1024,
        notes: 'Keep logos and text away from the top and bottom 14% to prevent them from being covered by overlays or CTAs.'
      },
      {
        id: 'ig-reel-ad-img',
        title: 'Reel Ad (Vertical)',
        dimensions: '1440×2560',
        width: 1440,
        height: 2560,
        aspectRatio: '9:16',
        format: 'Image',
        fileType: ['JPG', 'PNG'],
        maxFileSize: '30MB',
        maxFileSizeBytes: 30 * 1024 * 1024,
        notes: 'Keep logos and text away from the top and bottom 14% to prevent them from being covered by overlays or CTAs.'
      },
      {
        id: 'ig-story-ad-video',
        title: 'Story Ad (Vertical)',
        dimensions: '1440×2560',
        width: 1440,
        height: 2560,
        aspectRatio: '9:16',
        format: 'Video',
        fileType: ['MP4', 'MOV', 'GIF'],
        maxFileSize: '4GB',
        maxFileSizeBytes: 4 * 1024 * 1024 * 1024,
        settings: 'H.264 compression, square pixels, fixed frame rate, progressive scan and stereo AAC audio compression at 128kbps+.',
        notes: 'Keep logos and text away from the top and bottom 14% to prevent them from being covered by overlays or CTAs.'
      },
      {
        id: 'ig-reel-ad-video',
        title: 'Reel Ad (Vertical)',
        dimensions: '1440×2560',
        width: 1440,
        height: 2560,
        aspectRatio: '9:16',
        format: 'Video',
        fileType: ['MP4', 'MOV', 'GIF'],
        maxFileSize: '4GB',
        maxFileSizeBytes: 4 * 1024 * 1024 * 1024,
        settings: 'H.264 compression, square pixels, fixed frame rate, progressive scan and stereo AAC audio compression at 128kbps+.',
        notes: 'Keep logos and text away from the top and bottom 14% to prevent them from being covered by overlays or CTAs.'
      },
      {
        id: 'ig-carousel-sq',
        title: 'Carousel (Square)',
        dimensions: '1080×1080',
        width: 1080,
        height: 1080,
        aspectRatio: '1:1',
        format: 'Image',
        fileType: ['JPG', 'PNG'],
        maxFileSize: '30MB',
        maxFileSizeBytes: 30 * 1024 * 1024,
        notes: 'Consistent style across all images creates a cohesive narrative.'
      },
      {
        id: 'ig-carousel-vert',
        title: 'Carousel (Vertical)',
        dimensions: '1080×1350',
        width: 1080,
        height: 1350,
        aspectRatio: '4:5',
        format: 'Image',
        fileType: ['JPG', 'PNG'],
        maxFileSize: '30MB',
        maxFileSizeBytes: 30 * 1024 * 1024,
        notes: 'Prioritize mobile-friendly visuals for greater reach.'
      },
      {
        id: 'ig-explore',
        title: 'Explore Ad',
        dimensions: '1080×1080',
        width: 1080,
        height: 1080,
        aspectRatio: '1:1',
        format: 'Image',
        fileType: ['JPG', 'PNG'],
        maxFileSize: '30MB',
        maxFileSizeBytes: 30 * 1024 * 1024,
        notes: 'Appears in Explore tab among curated content. Great for discovery and reaching new audiences. Aspect ratio is 1:1 or 9:16.'
      },
      {
        id: 'ig-explore-video',
        title: 'Explore Ad',
        dimensions: '1080×1080',
        width: 1080,
        height: 1080,
        aspectRatio: '1:1',
        format: 'Video',
        fileType: ['MP4', 'MOV', 'GIF'],
        maxFileSize: '4GB',
        maxFileSizeBytes: 4 * 1024 * 1024 * 1024,
        settings: 'H.264 compression, square pixels, fixed frame rate, progressive scan and stereo AAC audio compression at 128kbps+.',
        notes: 'Video ads in Explore feed. Video captions and sound recommended. Aspect ratio is 1:1 or 9:16.'
      },
      {
        id: 'ig-search-img',
        title: 'Search Results Ad',
        dimensions: '1080×1080',
        width: 1080,
        height: 1080,
        aspectRatio: '1:1',
        format: 'Image',
        fileType: ['JPG', 'PNG'],
        maxFileSize: '30MB',
        maxFileSizeBytes: 30 * 1024 * 1024,
        notes: 'Appears in search results when users search for keywords in Instagram app. Aspect ratio is 1:1 or 1.91:1.'
      },
      {
        id: 'ig-search-video',
        title: 'Search Results Ad',
        dimensions: '1080×1080',
        width: 1080,
        height: 1080,
        aspectRatio: '1:1',
        format: 'Video',
        fileType: ['MP4', 'MOV', 'GIF'],
        maxFileSize: '4GB',
        maxFileSizeBytes: 4 * 1024 * 1024 * 1024,
        settings: 'H.264 compression, square pixels, fixed frame rate, progressive scan and stereo AAC audio compression at 128kbps+.',
        notes: 'Video ads in Instagram search results. Video captions and sound recommended. Aspect ratio is 1:1 or 1.91:1.'
      }
    ]
  },
  {
    id: 'facebook',
    name: 'Facebook',
    description: 'Facebook remains a central platform for personal connections and robust business marketing.',
    lastUpdated: '2025-07-14',
    specs: [
      {
        id: 'fb-profile',
        title: 'Profile Photo',
        dimensions: '320×320',
        width: 320,
        height: 320,
        aspectRatio: '1:1',
        format: 'Image',
        fileType: ['JPG', 'PNG'],
        maxFileSize: '30MB',
        maxFileSizeBytes: 30 * 1024 * 1024,
        notes: 'Displayed as a circle on profiles.'
      },
      {
        id: 'fb-cover',
        title: 'Cover Photo',
        dimensions: '851×315',
        width: 851,
        height: 315,
        aspectRatio: '16:9',
        format: 'Image',
        fileType: ['JPG', 'PNG'],
        maxFileSize: '30MB',
        maxFileSizeBytes: 30 * 1024 * 1024,
        notes: 'Mobile size: 640x360 px. Align text/visuals to the right.'
      },
      {
        id: 'fb-event-cover',
        title: 'Event Cover Photo',
        dimensions: '1920×1005',
        width: 1920,
        height: 1005,
        aspectRatio: '16:9',
        format: 'Image',
        fileType: ['JPG', 'PNG'],
        maxFileSize: '30MB',
        maxFileSizeBytes: 30 * 1024 * 1024,
        notes: 'High-resolution visuals create stronger impact for events.'
      },
      {
        id: 'fb-group-cover',
        title: 'Group Cover Photo',
        dimensions: '1640×856',
        width: 1640,
        height: 856,
        aspectRatio: '1.91:1',
        format: 'Image',
        fileType: ['JPG', 'PNG'],
        maxFileSize: '30MB',
        maxFileSizeBytes: 30 * 1024 * 1024,
        notes: 'Avoid cropping by maintaining the aspect ratio.'
      },
      {
        id: 'fb-feed',
        title: 'Feed Ad (Square)',
        dimensions: '1080×1080',
        width: 1080,
        height: 1080,
        aspectRatio: '1:1',
        format: 'Image',
        fileType: ['JPG', 'PNG'],
        maxFileSize: '30MB',
        maxFileSizeBytes: 30 * 1024 * 1024,
        notes: 'The standard ad format. Avoid heavy text.'
      },
      {
        id: 'fb-feed-vert',
        title: 'Feed Ad (Vertical)',
        dimensions: '1080×1350',
        width: 1080,
        height: 1350,
        aspectRatio: '4:5',
        format: 'Image',
        fileType: ['JPG', 'PNG'],
        maxFileSize: '30MB',
        maxFileSizeBytes: 30 * 1024 * 1024,
        notes: 'Stick to minimal text for improved performance.'
      },
      {
        id: 'fb-story-img',
        title: 'Story Image',
        dimensions: '1440×2560',
        width: 1440,
        height: 2560,
        aspectRatio: '9:16',
        format: 'Image',
        fileType: ['JPG', 'PNG'],
        maxFileSize: '30MB',
        maxFileSizeBytes: 30 * 1024 * 1024,
        notes: 'Leave a 250-pixel safe zone at top, 340-pixel safe zone at bottom for overlays.'
      },
      {
        id: 'fb-story-vid',
        title: 'Story Video',
        dimensions: '1440×2560',
        width: 1440,
        height: 2560,
        aspectRatio: '9:16',
        format: 'Video',
        fileType: ['MP4', 'MOV', 'GIF'],
        maxFileSize: '4GB',
        maxFileSizeBytes: 4 * 1024 * 1024 * 1024,
        settings: 'H.264 compression, square pixels, fixed frame rate, progressive scan and stereo AAC audio compression at 128kbps+.',
        notes: 'Leave a 250-pixel safe zone at top/bottom for overlays.'
      },
      {
        id: 'fb-story-ad-img',
        title: 'Story Ad (Vertical)',
        dimensions: '1440×2560',
        width: 1440,
        height: 2560,
        aspectRatio: '9:16',
        format: 'Image',
        fileType: ['JPG', 'PNG'],
        maxFileSize: '30MB',
        maxFileSizeBytes: 30 * 1024 * 1024,
        notes: 'Leave a 250-pixel safe zone at top/bottom for overlays.'
      },
      {
        id: 'fb-story-ad-vid',
        title: 'Story Ad (Vertical)',
        dimensions: '1440×2560',
        width: 1440,
        height: 2560,
        aspectRatio: '9:16',
        format: 'Video',
        fileType: ['MP4', 'MOV', 'GIF'],
        maxFileSize: '4GB',
        maxFileSizeBytes: 4 * 1024 * 1024 * 1024,
        settings: 'H.264 compression, square pixels, fixed frame rate, progressive scan and stereo AAC audio compression at 128kbps+.',
        notes: 'Leave a 250-pixel safe zone at top/bottom for overlays.'
      },
      {
        id: 'fb-reels',
        title: 'Reels',
        dimensions: '1440×2560',
        width: 1440,
        height: 2560,
        aspectRatio: '9:16',
        format: 'Video',
        fileType: ['MP4', 'MOV', 'GIF'],
        maxFileSize: '4GB',
        maxFileSizeBytes: 4 * 1024 * 1024 * 1024,
        settings: 'H.264 compression, square pixels, fixed frame rate, progressive scan and stereo AAC audio compression at 128kbps+.',
        notes: 'Vertical videos drive high engagement on Facebook.'
      },
      {
        id: 'fb-reel-ad-vert',
        title: 'Reel Ad (Vertical)',
        dimensions: '1440×2560',
        width: 1440,
        height: 2560,
        aspectRatio: '9:16',
        format: 'Image',
        fileType: ['JPG', 'PNG'],
        maxFileSize: '30MB',
        maxFileSizeBytes: 30 * 1024 * 1024,
        notes: 'Leave a 250-pixel safe zone at top, 340-pixel safe zone at bottom for overlays.'
      },
      {
        id: 'fb-video-feed',
        title: 'In-Stream Video Ad',
        dimensions: '1080×1080',
        width: 1080,
        height: 1080,
        aspectRatio: '1:1',
        format: 'Video',
        fileType: ['MP4', 'MOV', 'GIF'],
        maxFileSize: '4GB',
        maxFileSizeBytes: 4 * 1024 * 1024 * 1024,
        settings: 'H.264 compression, square pixels, fixed frame rate, progressive scan and stereo AAC audio compression at 128kbps+.',
        notes: 'Appears in Facebook Live feeds after 1+ minute. Mobile only. Can use carousel format with 2-10 videos. Aspect ratio is 1:1 or 4:5.'
      },
      {
        id: 'fb-marketplace',
        title: 'Marketplace Ad',
        dimensions: '1080×1080',
        width: 1080,
        height: 1080,
        aspectRatio: '1:1',
        format: 'Image',
        fileType: ['JPG', 'PNG'],
        maxFileSize: '30MB',
        maxFileSizeBytes: 30 * 1024 * 1024,
        notes: 'Image-only format for Marketplace. Also appears in feed through Advantage+ placement. Clear product photos perform best.'
      },
      {
        id: 'fb-search',
        title: 'Search Results Ad',
        dimensions: '1080×1080',
        width: 1080,
        height: 1080,
        aspectRatio: '1:1',
        format: 'Image',
        fileType: ['JPG', 'PNG'],
        maxFileSize: '30MB',
        maxFileSizeBytes: 30 * 1024 * 1024,
        notes: 'Appears in Facebook and Marketplace search results. If including a link, limited to 1:1 ratio.'
      },
      {
        id: 'fb-explore',
        title: 'Business Explore Ad',
        dimensions: '1080×1080',
        width: 1080,
        height: 1080,
        aspectRatio: '1:1',
        format: 'Image',
        fileType: ['JPG', 'PNG'],
        maxFileSize: '30MB',
        maxFileSizeBytes: 30 * 1024 * 1024,
        notes: 'Appears when someone taps a business post header (mobile only). Primary text up to 125 characters.'
      },
      {
        id: 'fb-explore-vid',
        title: 'Business Explore Ad',
        dimensions: '1080×1080',
        width: 1080,
        height: 1080,
        aspectRatio: '1:1',
        format: 'Video',
        fileType: ['MP4', 'MOV', 'GIF'],
        maxFileSize: '4GB',
        maxFileSizeBytes: 4 * 1024 * 1024 * 1024,
        settings: 'H.264 compression, square pixels, fixed frame rate, progressive scan and stereo AAC audio compression at 128kbps+.',
        notes: 'Appears when someone taps a business post header (mobile only). Primary text up to 125 characters.'
      },
      {
        id: 'fb-collection-img',
        title: 'Collection Ad',
        dimensions: '1080×1080',
        width: 1080,
        height: 1080,
        aspectRatio: '1:1',
        format: 'Image',
        fileType: ['JPG', 'PNG'],
        maxFileSize: '30MB',
        maxFileSizeBytes: 30 * 1024 * 1024,
        notes: 'Auto-generated from product catalog. Cover image/video plus 3 product images. Opens Instant Experience.'
      },
      {
        id: 'fb-collection-vid',
        title: 'Collection Ad',
        dimensions: '1080×1080',
        width: 1080,
        height: 1080,
        aspectRatio: '1:1',
        format: 'Video',
        fileType: ['MP4', 'MOV', 'GIF'],
        maxFileSize: '4GB',
        maxFileSizeBytes: 4 * 1024 * 1024 * 1024,
        settings: 'H.264 compression, square pixels, fixed frame rate, progressive scan and stereo AAC audio compression at 128kbps+.',
        notes: 'Cover video plus product images. Recommended cover video length under 2 minutes.'
      },
      {
        id: 'fb-carousel',
        title: 'Carousel Images',
        dimensions: '1080×1080',
        width: 1080,
        height: 1080,
        aspectRatio: '1:1',
        format: 'Image',
        fileType: ['JPG', 'PNG'],
        maxFileSize: '30MB',
        maxFileSizeBytes: 30 * 1024 * 1024,
        notes: 'Up to 10 images can be included; consistency is key for storytelling.'
      },
      {
        id: 'fb-right-col',
        title: 'Right Column Ad',
        dimensions: '1080×1080',
        width: 1080,
        height: 1080,
        aspectRatio: '1:1',
        format: 'Image',
        fileType: ['JPG', 'PNG'],
        maxFileSize: '30MB',
        maxFileSizeBytes: 30 * 1024 * 1024,
        notes: 'Desktop only. Recommended min size is 254x133 px.'
      }
    ]
  },
  {
    id: 'twitter',
    name: 'X (Twitter)',
    description: 'Real-time information network for concise communication and breaking news.',
    lastUpdated: '2025-06-29',
    specs: [
      {
        id: 'x-profile',
        title: 'Profile Photo',
        dimensions: '400×400',
        width: 400,
        height: 400,
        aspectRatio: '1:1',
        format: 'Image',
        fileType: ['JPG', 'PNG'],
        maxFileSize: '5MB',
        maxFileSizeBytes: 5 * 1024 * 1024,
        notes: 'Min size: 200x200 px. Displayed as circle.'
      },
      {
        id: 'x-header',
        title: 'Header (Cover) Photo',
        dimensions: '1500×500',
        width: 1500,
        height: 500,
        aspectRatio: '3:1',
        format: 'Image',
        fileType: ['JPG', 'PNG'],
        maxFileSize: '5MB',
        maxFileSizeBytes: 5 * 1024 * 1024,
        notes: 'Ensure key content is centered, as edges may be cropped.'
      },
      {
        id: 'x-feed-image',
        title: 'In-Feed Image',
        dimensions: '1600×900',
        width: 1600,
        height: 900,
        aspectRatio: '1.91:1',
        format: 'Image',
        fileType: ['JPG', 'PNG'],
        maxFileSize: '5MB',
        maxFileSizeBytes: 5 * 1024 * 1024,
        notes: 'Can use 1200x1200 (1:1), 1200x628 (1.91:1), or 1080x1350 (4:5).'
      },
      {
        id: 'x-feed-video',
        title: 'In-Feed Video',
        dimensions: '1600×900',
        width: 1600,
        height: 900,
        aspectRatio: '16:9',
        format: 'Video',
        fileType: ['MP4', 'MOV'],
        maxFileSize: '1GB',
        maxFileSizeBytes: 1 * 1024 * 1024 * 1024,
        settings: 'Audio codec: AAC LC (low complexity). Video codec recommendation: H264, Baseline, Main, or High Profile with a 4:2:0 color space.',
        notes: 'Maximum file size: 512 MB.'
      },
      {
        id: 'x-card',
        title: 'Website Card Image',
        dimensions: '800×418',
        width: 800,
        height: 418,
        aspectRatio: '1.91:1',
        format: 'Image',
        fileType: ['JPG', 'PNG'],
        maxFileSize: '5MB',
        maxFileSizeBytes: 5 * 1024 * 1024,
        notes: 'Used for website preview cards and ads. Single image tweets use 1200x628.'
      },
      {
        id: 'x-image-ad',
        title: 'Image Ad',
        dimensions: '800×418',
        width: 800,
        height: 418,
        aspectRatio: '1.91:1',
        format: 'Image',
        fileType: ['JPG', 'PNG'],
        maxFileSize: '5MB',
        maxFileSizeBytes: 5 * 1024 * 1024,
        notes: 'Used for website preview cards and ads. Single image tweets use 1200x628.'
      },
      {
        id: 'x-carousel-img',
        title: 'Carousel Ad',
        dimensions: '800×418',
        width: 800,
        height: 418,
        aspectRatio: '1.91:1',
        format: 'Image',
        fileType: ['JPG', 'PNG'],
        maxFileSize: '5MB',
        maxFileSizeBytes: 5 * 1024 * 1024,
        notes: 'Can also use 1:1 ratio (800x800). Supports images and videos.'
      },
      {
        id: 'x-carousel-video',
        title: 'Carousel Ad',
        dimensions: '800×418',
        width: 800,
        height: 418,
        aspectRatio: '1.91:1',
        format: 'Video',
        fileType: ['MP4', 'MOV'],
        maxFileSize: '1GB',
        maxFileSizeBytes: 1 * 1024 * 1024 * 1024,
        settings: 'Audio codec: AAC LC (low complexity). Video codec recommendation: H264, Baseline, Main, or High Profile with a 4:2:0 color space.',
        notes: 'Can also use 1:1 ratio (800x800). Supports images and videos.'
      },
      {
        id: 'x-video-ad',
        title: 'Video Ad',
        dimensions: '1600×900',
        width: 1600,
        height: 900,
        aspectRatio: '16:9',
        format: 'Video',
        fileType: ['MP4', 'MOV'],
        maxFileSize: '1GB',
        maxFileSizeBytes: 1 * 1024 * 1024 * 1024,
        settings: 'Audio codec: AAC LC (low complexity). Video codec: H.264, Baseline/Main/High Profile, 4:2:0 color space. Progressive scan. Stereo audio. Max bitrate: 25 Mbps.',
        notes: 'In-feed video ads appear directly in the timeline. Recommended duration: 6-120 seconds (max 2 min 20 sec). Resolution: 1920x1080 or 1280x720 also accepted. Up to 1GB (recommended under 512MB).'
      }
    ]
  },
  {
    id: 'linkedin',
    name: 'LinkedIn',
    description: 'The professional networking platform for B2B marketing and career development.',
    lastUpdated: '2025-06-29',
    specs: [
      {
        id: 'li-profile',
        title: 'Profile Photo',
        dimensions: '400×400',
        width: 400,
        height: 400,
        aspectRatio: '1:1',
        format: 'Image',
        fileType: ['JPG', 'PNG', 'GIF'],
        maxFileSize: '5MB',
        maxFileSizeBytes: 5 * 1024 * 1024,
        notes: 'Displayed as a circle; upload a high-quality image for clarity.'
      },
      {
        id: 'li-cover',
        title: 'Personal Cover Photo',
        dimensions: '1584×396',
        width: 1584,
        height: 396,
        aspectRatio: '4:1',
        format: 'Image',
        fileType: ['JPG', 'PNG', 'GIF'],
        maxFileSize: '5MB',
        maxFileSizeBytes: 5 * 1024 * 1024,
        notes: 'Ensure key visuals are centered as cropping may occur.'
      },
      {
        id: 'li-company-logo',
        title: 'Company Logo',
        dimensions: '400×400',
        width: 400,
        height: 400,
        aspectRatio: '1:1',
        format: 'Image',
        fileType: ['JPG', 'PNG', 'GIF'],
        maxFileSize: '5MB',
        maxFileSizeBytes: 5 * 1024 * 1024,
        notes: 'Previously 300×300. Displayed on company pages and ads.'
      },
      {
        id: 'li-company-cover',
        title: 'Company Cover Photo',
        dimensions: '1128×191',
        width: 1128,
        height: 191,
        aspectRatio: '5.91:1',
        format: 'Image',
        fileType: ['JPG', 'PNG', 'GIF'],
        maxFileSize: '5MB',
        maxFileSizeBytes: 5 * 1024 * 1024,
        notes: 'High-quality image recommended to avoid pixelation.'
      },
      {
        id: 'li-post-rec',
        title: 'Post Image (Rec.)',
        dimensions: '1200×627',
        width: 1200,
        height: 627,
        aspectRatio: '1.91:1',
        format: 'Image',
        fileType: ['JPG', 'PNG', 'GIF'],
        maxFileSize: '5MB',
        maxFileSizeBytes: 5 * 1024 * 1024,
        notes: 'Recommended for shared link previews and single image posts.'
      },
      {
        id: 'li-post-sq',
        title: 'Post (Square)',
        dimensions: '1080×1080',
        width: 1080,
        height: 1080,
        aspectRatio: '1:1',
        format: 'Image',
        fileType: ['JPG', 'PNG', 'GIF'],
        maxFileSize: '5MB',
        maxFileSizeBytes: 5 * 1024 * 1024,
        notes: 'Ideal for general updates and balanced visuals.'
      },
      {
        id: 'li-post-vert',
        title: 'Post (Vertical)',
        dimensions: '1080×1350',
        width: 1080,
        height: 1350,
        aspectRatio: '4:5',
        format: 'Image',
        fileType: ['JPG', 'PNG', 'GIF'],
        maxFileSize: '5MB',
        maxFileSizeBytes: 5 * 1024 * 1024,
        notes: 'Optimized for mobile viewing, but might be cropped on desktop.'
      },
      {
        id: 'li-video-post',
        title: 'Video Post',
        dimensions: '4096×2304',
        width: 4096,
        height: 2304,
        aspectRatio: '1:2.4',
        format: 'Video',
        fileType: ['MP4'],
        maxFileSize: '500MB',
        maxFileSizeBytes: 500 * 1024 * 1024,
        settings: 'Video Sound Format: AAC or MPEG4. Recommended frame rate: 30 fps. Video Sound Rate: Less than 64 KHz.',
        notes: 'Supports various ratios like 4:5, 9:16, 16:9, and 1:1. 256×144 to 4096×2304.'
      },
      {
        id: 'li-article-cover',
        title: 'Article Cover',
        dimensions: '1920×1080',
        width: 1920,
        height: 1080,
        aspectRatio: '16:9',
        format: 'Image',
        fileType: ['JPG', 'PNG', 'GIF'],
        maxFileSize: '5MB',
        maxFileSizeBytes: 5 * 1024 * 1024,
        notes: 'Recommended for long-form content for a professional header.'
      },
      {
        id: 'li-single-image',
        title: 'Single Image Ad',
        dimensions: '1200×1200',
        width: 1200,
        height: 1200,
        aspectRatio: '1:1',
        format: 'Image',
        fileType: ['JPG', 'PNG', 'GIF'],
        maxFileSize: '5MB',
        maxFileSizeBytes: 5 * 1024 * 1024,
        notes: 'Vertical ads (4:5) only deliver on mobile. Aspect ratio is 1:1, 1.91:1 or 4:5.'
      },
      {
        id: 'li-video-ad',
        title: 'Video Ad',
        dimensions: '1920×1080',
        width: 1920,
        height: 1080,
        aspectRatio: '16:9',
        format: 'Video',
        fileType: ['MP4'],
        maxFileSize: '500MB',
        maxFileSizeBytes: 500 * 1024 * 1024,
        settings: 'AAC or MPEG-4 audio <64 KHz; frame rate <30 fps; duration 3 s–30 min; width/height: 360–1920 px.',
        notes: 'Custom thumbnail optional: JPG/PNG ≤2 MB, matching aspect ratio. Aspect ratio is 1:1, 1.91:1, 4:5, 9:16 or 16:9.'
      },
      {
        id: 'li-event-ad',
        title: 'Event Ad',
        dimensions: '1920×480',
        width: 1920,
        height: 480,
        aspectRatio: '4:1',
        format: 'Image',
        fileType: ['JPG', 'PNG'],
        maxFileSize: '5MB',
        maxFileSizeBytes: 5 * 1024 * 1024,
        notes: 'Event name ≤255 chars; intro text ≤600 chars; link to LinkedIn Event page.'
      },
      {
        id: 'li-ctv-ad',
        title: 'Connected TV Ad',
        dimensions: '1920×1080',
        width: 1920,
        height: 1080,
        aspectRatio: '16:9',
        format: 'Video',
        fileType: ['MP4'],
        maxFileSize: '500MB',
        maxFileSizeBytes: 500 * 1024 * 1024,
        settings: 'Bitrate 15-40 Mbps; PCM or AAC 48 kHz ≥192 kbps; duration 6–60 s; frame rate 23.98–30 fps;',
        notes: '1280×720 to 1920×1080 px. Recommended: 16:9 aspect ratio.'
      },
      {
        id: 'li-carousel',
        title: 'Carousel Ad',
        dimensions: '1080×1080',
        width: 1080,
        height: 1080,
        aspectRatio: '1:1',
        format: 'Image',
        fileType: ['JPG', 'PNG', 'GIF'],
        maxFileSize: '5MB',
        maxFileSizeBytes: 5 * 1024 * 1024,
        notes: 'Maintain consistent design across all slides. Can use up to 10 cards.'
      }
    ]
  },
  {
    id: 'threads',
    name: 'Threads',
    description: 'Threads offers a dynamic and engaging environment focused on text-based discussions and visual sharing.',
    lastUpdated: '2025-06-17',
    specs: [
      {
        id: 'threads-profile',
        title: 'Profile Photo',
        dimensions: '320×320',
        width: 320,
        height: 320,
        aspectRatio: '1:1',
        format: 'Image',
        fileType: ['JPG', 'PNG'],
        maxFileSize: '30MB',
        maxFileSizeBytes: 30 * 1024 * 1024,
        notes: 'Displayed as a circle; ensure the focal point is centered. Same as Instagram.'
      },
      {
        id: 'threads-post',
        title: 'Post Images',
        dimensions: '1080×1350',
        width: 1080,
        height: 1350,
        aspectRatio: '4:5',
        format: 'Image',
        fileType: ['JPG', 'PNG'],
        maxFileSize: '30MB',
        maxFileSizeBytes: 30 * 1024 * 1024,
        notes: 'Also supports 1.91:1 and 1:1. Use 1080px width for best results.'
      },
      {
        id: 'threads-carousel',
        title: 'Carousel Content (Image)',
        dimensions: '1080×1350',
        width: 1080,
        height: 1350,
        aspectRatio: '4:5',
        format: 'Image',
        fileType: ['JPG', 'PNG'],
        maxFileSize: '30MB',
        maxFileSizeBytes: 30 * 1024 * 1024,
        notes: 'Up to 10 photos allowed per post. Aspect ratio is 1:1, 1.91:1 or 4:5.'
      },
      {
        id: 'threads-carousel-video',
        title: 'Carousel Content (Video)',
        dimensions: '1080×1350',
        width: 1080,
        height: 1350,
        aspectRatio: '4:5',
        format: 'Video',
        fileType: ['MP4', 'MOV', 'GIF'],
        maxFileSize: '4GB',
        maxFileSizeBytes: 4 * 1024 * 1024 * 1024,
        settings: 'H.264 compression, square pixels, fixed frame rate, progressive scan and stereo AAC audio compression at 128kbps+.',
        notes: 'Videos are optimized for mobile consumption and seamless playback. Aspect ratio is 1:1, 1.91:1 or 4:5.'
      },
      {
        id: 'threads-video',
        title: 'Post Videos',
        dimensions: '1080×1350',
        width: 1080,
        height: 1350,
        aspectRatio: '4:5',
        format: 'Video',
        fileType: ['MP4', 'MOV', 'GIF'],
        maxFileSize: '4GB',
        maxFileSizeBytes: 4 * 1024 * 1024 * 1024,
        settings: 'H.264 compression, square pixels, fixed frame rate, progressive scan and stereo AAC audio compression at 128kbps+.',
        notes: 'Max video length 5 minutes. Use same aspect ratios as images.'
      }
    ]
  },
  {
    id: 'pinterest',
    name: 'Pinterest',
    description: 'A powerful visual discovery engine and digital mood board. Platforms for inspiration and future planning.',
    lastUpdated: '2025-06-29',
    specs: [
      {
        id: 'pin-profile',
        title: 'Profile Photo',
        dimensions: '165×165',
        width: 165,
        height: 165,
        aspectRatio: '1:1',
        format: 'Image',
        fileType: ['JPG', 'PNG'],
        maxFileSize: '20MB',
        maxFileSizeBytes: 20 * 1024 * 1024,
        notes: 'Displayed as a circle; keep the focal point centered.'
      },
      {
        id: 'pin-cover',
        title: 'Profile Cover Photo',
        dimensions: '800×450',
        width: 800,
        height: 450,
        aspectRatio: '16:9',
        format: 'Image',
        fileType: ['JPG', 'PNG'],
        maxFileSize: '20MB',
        maxFileSizeBytes: 20 * 1024 * 1024,
        notes: 'Minimum dimensions. Higher resolution is better.'
      },
      {
        id: 'pin-standard',
        title: 'Standard Pin',
        dimensions: '1000×1500',
        width: 1000,
        height: 1500,
        aspectRatio: '2:3',
        format: 'Image',
        fileType: ['JPG', 'PNG'],
        maxFileSize: '20MB',
        maxFileSizeBytes: 20 * 1024 * 1024,
        notes: 'Recommended ratio for optimal display in users\' feeds.'
      },
      {
        id: 'pin-square',
        title: 'Square Pin',
        dimensions: '1000×1000',
        width: 1000,
        height: 1000,
        aspectRatio: '1:1',
        format: 'Image',
        fileType: ['JPG', 'PNG'],
        maxFileSize: '20MB',
        maxFileSizeBytes: 20 * 1024 * 1024,
        notes: 'Works well for product images or infographics.'
      },
      {
        id: 'pin-long',
        title: 'Long Pin',
        dimensions: '1000×2100',
        width: 1000,
        height: 2100,
        aspectRatio: '1:2.1',
        format: 'Image',
        fileType: ['JPG', 'PNG'],
        maxFileSize: '20MB',
        maxFileSizeBytes: 20 * 1024 * 1024,
        notes: 'Great for step-by-step tutorials; can get cut off in feeds if too long.'
      },
      {
        id: 'pin-idea-img',
        title: 'Idea Pin (Story) - Image',
        dimensions: '1080×1920',
        width: 1080,
        height: 1920,
        aspectRatio: '9:16',
        format: 'Image',
        fileType: ['JPG', 'PNG'],
        maxFileSize: '20MB',
        maxFileSizeBytes: 20 * 1024 * 1024,
        notes: 'Ideal for immersive, full-screen experiences.'
      },
      {
        id: 'pin-idea-vid',
        title: 'Idea Pin (Story) - Video',
        dimensions: '1080×1920',
        width: 1080,
        height: 1920,
        aspectRatio: '9:16',
        format: 'Video',
        fileType: ['MP4', 'MOV', 'M4V'],
        maxFileSize: '32MB',
        maxFileSizeBytes: 32 * 1024 * 1024,
        settings: 'Encoding: H.264 or H.265.',
        notes: 'Ideal for immersive, full-screen experiences.'
      },
      {
        id: 'pin-single-ad',
        title: 'Single Image Ad',
        dimensions: '1000×1500',
        width: 1000,
        height: 1500,
        aspectRatio: '2:3',
        format: 'Image',
        fileType: ['JPG', 'PNG'],
        maxFileSize: '20MB',
        maxFileSizeBytes: 20 * 1024 * 1024,
        notes: 'Static image ads. Use the same specs as standard or square pins. Aspect ratio is 1:1 or 2:3.'
      },
      {
        id: 'pin-carousel',
        title: 'Carousel Ad',
        dimensions: '1000×1500',
        width: 1000,
        height: 1500,
        aspectRatio: '2:3',
        format: 'Image',
        fileType: ['JPG', 'PNG'],
        maxFileSize: '20MB',
        maxFileSizeBytes: 20 * 1024 * 1024,
        notes: '2-5 images per carousel. Each slide should maintain the same aspect ratio. 1000×1500px or 1000×1000px.'
      },
      {
        id: 'pin-idea-ad-img',
        title: 'Idea Ad (Image)',
        dimensions: '1080×1920',
        width: 1080,
        height: 1920,
        aspectRatio: '9:16',
        format: 'Image',
        fileType: ['BMP', 'JPEG', 'PNG', 'TIFF', 'WEBP'],
        maxFileSize: '20MB',
        maxFileSizeBytes: 20 * 1024 * 1024,
        notes: 'Recommended 1080 × 1920 px size (9:16 ratio) for full-bleed imagery.'
      },
      {
        id: 'pin-idea-ad-vid',
        title: 'Idea Ad (Video)',
        dimensions: '1080×1920',
        width: 1080,
        height: 1920,
        aspectRatio: '9:16',
        format: 'Video',
        fileType: ['MP4', 'MOV', 'M4V'],
        maxFileSize: '100MB',
        maxFileSizeBytes: 100 * 1024 * 1024,
        settings: 'Encoding: H.264 or H.265.',
        notes: 'Duration ≤5min. Up to 100MB web / 2GB mobile.'
      },
      {
        id: 'pin-showcase-img',
        title: 'Showcase Ad (Image)',
        dimensions: '1000×1500',
        width: 1000,
        height: 1500,
        aspectRatio: '2:3',
        format: 'Image',
        fileType: ['BMP', 'JPEG', 'PNG', 'TIFF', 'WEBP'],
        maxFileSize: '32MB',
        maxFileSizeBytes: 32 * 1024 * 1024,
        notes: '1 title + up to 4 cards. Aspect ratio is 1:1 or 2:3.'
      },
      {
        id: 'pin-showcase-vid',
        title: 'Showcase Ad (Video)',
        dimensions: '1000×1500',
        width: 1000,
        height: 1500,
        aspectRatio: '2:3',
        format: 'Video',
        fileType: ['MP4', 'MOV', 'M4V'],
        maxFileSize: '32MB',
        maxFileSizeBytes: 32 * 1024 * 1024,
        settings: 'Encoding: H.264 or H.265. 3-60s duration.',
        notes: '1 title + up to 4 cards. Aspect ratio is 1:1 or 2:3.'
      },
      {
        id: 'pin-quiz',
        title: 'Quiz Ad',
        dimensions: '1000×1500',
        width: 1000,
        height: 1500,
        aspectRatio: '2:3',
        format: 'Image',
        fileType: ['BMP', 'JPEG', 'PNG', 'TIFF', 'WEBP'],
        maxFileSize: '32MB',
        maxFileSizeBytes: 32 * 1024 * 1024,
        notes: '1 title + up to 3 result cards.'
      },
      {
        id: 'pin-board-cover',
        title: 'Board Cover',
        dimensions: '600×600',
        width: 600,
        height: 600,
        aspectRatio: '1:1',
        format: 'Image',
        fileType: ['JPG', 'PNG'],
        maxFileSize: '20MB',
        maxFileSizeBytes: 20 * 1024 * 1024,
        notes: 'Use simple, bold images that represent the board\'s theme.'
      }
    ]
  },
  {
    id: 'youtube',
    name: 'YouTube',
    description: 'The undisputed global leader in video-sharing and long-form content.',
    lastUpdated: '2025-06-29',
    specs: [
      {
        id: 'yt-video',
        title: 'Video (HD)',
        dimensions: '1920×1080',
        width: 1920,
        height: 1080,
        aspectRatio: '16:9',
        format: 'Video',
        fileType: ['MP4', 'MOV', 'AVI', 'MPEG'],
        maxFileSize: '256GB',
        maxFileSizeBytes: 256 * 1024 * 1024 * 1024,
        settings: 'MPEG-2 (Audio codec: MPEG Layer II or Dolby AC-3. Audio bitrate: 128 kbps or better).',
        notes: 'Minimum HD resolution for all uploads.'
      },
      {
        id: 'yt-display',
        title: 'Display Ad',
        dimensions: '300×250',
        width: 300,
        height: 250,
        aspectRatio: '1.2:1',
        format: 'Image',
        fileType: ['JPG', 'PNG', 'GIF'],
        maxFileSize: '5MB',
        maxFileSizeBytes: 5 * 1024 * 1024,
        notes: 'Appears on the right of a featured video on desktop.'
      },
      {
        id: 'yt-overlay',
        title: 'Overlay Ad',
        dimensions: '480×70',
        width: 480,
        height: 70,
        aspectRatio: '6.86:1',
        format: 'Image',
        fileType: ['JPG', 'PNG', 'GIF'],
        maxFileSize: '5MB',
        maxFileSizeBytes: 5 * 1024 * 1024,
        notes: 'Semi-transparent ad on the lower 20% of a video.'
      },
      {
        id: 'yt-thumbnail',
        title: 'Video Thumbnail',
        dimensions: '1280×720',
        width: 1280,
        height: 720,
        aspectRatio: '16:9',
        format: 'Image',
        fileType: ['JPG', 'PNG', 'GIF'],
        maxFileSize: '5MB',
        maxFileSizeBytes: 5 * 1024 * 1024,
        notes: 'Have a resolution of 1280x720 (with min width of 640 pixels). Remain under 2MB. Use a 16:9 aspect ratio.'
      },
      {
        id: 'yt-skippable',
        title: 'Skippable In-Stream Ad',
        dimensions: '1920×1080',
        width: 1920,
        height: 1080,
        aspectRatio: '16:9',
        format: 'Video',
        fileType: ['MP4', 'MOV', 'AVI'],
        maxFileSize: '256GB',
        maxFileSizeBytes: 256 * 1024 * 1024 * 1024,
        notes: 'HD recommended (1280x720). Any length (best practice 12s+ to count as view). Captions supported.'
      },
      {
        id: 'yt-non-skippable',
        title: 'Non-Skippable In-Stream Ad',
        dimensions: '1920×1080',
        width: 1920,
        height: 1080,
        aspectRatio: '16:9',
        format: 'Video',
        fileType: ['MP4', 'MOV', 'AVI'],
        maxFileSize: '256GB',
        maxFileSizeBytes: 256 * 1024 * 1024 * 1024,
        notes: '15-20s (TV up to 30s); HD recommended.'
      },
      {
        id: 'yt-bumper',
        title: 'Bumper Ad',
        dimensions: '1920×1080',
        width: 1920,
        height: 1080,
        aspectRatio: '16:9',
        format: 'Video',
        fileType: ['MP4', 'MOV', 'AVI'],
        maxFileSize: '256GB',
        maxFileSizeBytes: 256 * 1024 * 1024 * 1024,
        notes: '≤ 6s; non-skippable; HD recommended.'
      },
      {
        id: 'yt-in-feed',
        title: 'In-Feed Video Ad',
        dimensions: '1080×1080',
        width: 1080,
        height: 1080,
        aspectRatio: '1:1',
        format: 'Video',
        fileType: ['MP4', 'MOV', 'AVI'],
        maxFileSize: '256GB',
        maxFileSizeBytes: 256 * 1024 * 1024 * 1024,
        notes: '15s recommended; min HD; thumbnails must be 1280x720. Aspect ratio is 16:9, 1:1 or 9:16.'
      },
      {
        id: 'yt-masthead',
        title: 'YouTube Masthead Ad',
        dimensions: '1920×1080',
        width: 1920,
        height: 1080,
        aspectRatio: '16:9',
        format: 'Video',
        fileType: ['MP4', 'MOV', 'AVI'],
        maxFileSize: '256GB',
        maxFileSizeBytes: 256 * 1024 * 1024 * 1024,
        notes: 'Any length; reservation only; auto-plays muted (desktop: ≤30s preview; mobile full duration).'
      },
      {
        id: 'yt-shorts',
        title: 'YouTube Shorts Ad',
        dimensions: '1080×1920',
        width: 1080,
        height: 1920,
        aspectRatio: '9:16',
        format: 'Video',
        fileType: ['MP4', 'MOV', 'AVI'],
        maxFileSize: '256GB',
        maxFileSizeBytes: 256 * 1024 * 1024 * 1024, 
        notes: '6s min; 10-60s recommended; users can swipe away.'
      }
    ]
  },
  {
    id: 'tiktok',
    name: 'TikTok',
    description: 'Revolutionized social media with short-form, authentic video content.',
    lastUpdated: '2025-06-17',
    specs: [
      {
        id: 'tt-profile',
        title: 'Profile Photo',
        dimensions: '200×200',
        width: 200,
        height: 200,
        aspectRatio: '1:1',
        format: 'Image',
        fileType: ['JPG', 'PNG'],
        maxFileSize: '100KB',
        maxFileSizeBytes: 100 * 1024,
        notes: 'Minimum upload size is 20x20 px. Displayed as circle.'
      },
      {
        id: 'tt-feed',
        title: 'In-Feed Video',
        dimensions: '1080×1920',
        width: 1080,
        height: 1920,
        aspectRatio: '9:16',
        format: 'Video',
        fileType: ['MP4', 'MOV', 'MPEG'],
        maxFileSize: '500MB',
        maxFileSizeBytes: 500 * 1024 * 1024,
        settings: 'Bitrate: ≥2,500kbps.',
        notes: 'Recommended size. Other dimensions will have black bars added for full-screen display.'
      },
      {
        id: 'tt-feed-ad-img',
        title: 'In-Feed Ad',
        dimensions: '1080×1920',
        width: 1080,
        height: 1920,
        aspectRatio: '9:16',
        format: 'Image',
        fileType: ['JPG', 'PNG'],
        maxFileSize: '100KB',
        maxFileSizeBytes: 100 * 1024,
        notes: 'Vertical (9:16) is highly recommended for best performance. Aspect ratio is 16:9, 1:1 or 9:16.'
      },
      {
        id: 'tt-feed-ad-vid',
        title: 'In-Feed Ad',
        dimensions: '1080×1920',
        width: 1080,
        height: 1920,
        aspectRatio: '9:16',
        format: 'Video',
        fileType: ['MP4', 'MOV', 'MPEG'],
        maxFileSize: '500MB',
        maxFileSizeBytes: 500 * 1024 * 1024,
        settings: 'Bitrate: ≥2,500kbps.',
        notes: 'Vertical (9:16) is highly recommended for best performance. Aspect ratio is 16:9, 1:1 or 9:16.'
      },
      {
        id: 'tt-carousel',
        title: 'Image Ad (Carousel)',
        dimensions: '1200×628',
        width: 1200,
        height: 628,
        aspectRatio: '1.91:1',
        format: 'Image',
        fileType: ['JPG', 'PNG'],
        maxFileSize: '100KB',
        maxFileSizeBytes: 100 * 1024,
        notes: 'For ads in the news feed app series. Max file size 100 MB per image. 1200x628 or 1080x1080 px recommended. Aspect ratio is 1.91:1 or 1:1.'
      }
    ]
  },
  {
    id: 'twitch',
    name: 'Twitch',
    description: 'The world\'s leading live streaming platform, primarily focused on video gaming and IRL streams.',
    lastUpdated: '2025-06-29',
    specs: [
      {
        id: 'tw-profile',
        title: 'Profile Photo',
        dimensions: '800×800',
        width: 800,
        height: 800,
        aspectRatio: '1:1',
        format: 'Image',
        fileType: ['JPG', 'PNG'],
        maxFileSize: '10MB',
        maxFileSizeBytes: 10 * 1024 * 1024,
        notes: 'Displayed as a circle. Ensure key elements are centered.'
      },
      {
        id: 'tw-banner',
        title: 'Profile Banner',
        dimensions: '1200×480',
        width: 1200,
        height: 480,
        aspectRatio: '5:2',
        format: 'Image',
        fileType: ['JPG', 'PNG'],
        maxFileSize: '10MB',
        maxFileSizeBytes: 10 * 1024 * 1024,
        notes: 'Header at the top of your channel page. Keep key info away from edges.'
      },
      {
        id: 'tw-offline',
        title: 'Offline Banner',
        dimensions: '1920×1080',
        width: 1920,
        height: 1080,
        aspectRatio: '16:9',
        format: 'Image',
        fileType: ['JPG', 'PNG'],
        maxFileSize: '10MB',
        maxFileSizeBytes: 10 * 1024 * 1024,
        notes: 'Displayed in the video player when the channel is offline.'
      },
      {
        id: 'tw-thumbnail',
        title: 'Video Thumbnail',
        dimensions: '1280×720',
        width: 1280,
        height: 720,
        aspectRatio: '16:9',
        format: 'Image',
        fileType: ['JPG', 'PNG'],
        maxFileSize: '10MB',
        maxFileSizeBytes: 10 * 1024 * 1024,
        notes: 'Thumbnail for past broadcasts (VODs) and highlights.'
      },
      {
        id: 'tw-takeover',
        title: 'First Impression Takeover Ad',
        dimensions: '1920×1080',
        width: 1920,
        height: 1080,
        aspectRatio: '16:9',
        format: 'Video',
        fileType: ['MP4', 'H.264'],
        maxFileSize: 'N/A',
        settings: 'bitrate 4000-10000kbps; 24-30fps; also require multi-bitrate VAST encodes at 1920×1080, 1280×720, 854×480, 640×360, 284×160',
        notes: '≤30s unskippable.'
      },
      {
        id: 'tw-headliner-desk',
        title: 'Homepage Headliner Ad',
        dimensions: '450×350',
        width: 450,
        height: 350,
        aspectRatio: '1.29:1',
        format: 'Image',
        fileType: ['JPG', 'PNG'],
        maxFileSize: '150KB',
        maxFileSizeBytes: 150 * 1024,
        notes: 'Desktop Left/Right. Static images, no animation; paired left + right plus hex color background'
      },
      {
        id: 'tw-headliner-mob',
        title: 'Homepage Headliner Ad',
        dimensions: '640×100',
        width: 640,
        height: 100,
        aspectRatio: '6.4:1',
        format: 'Image',
        fileType: ['JPG', 'PNG'],
        maxFileSize: '350KB',
        maxFileSizeBytes: 350 * 1024,
        notes: 'Mobile Banner.Static mobile banner on Following tab.'
      },
      {
        id: 'tw-headliner-full',
        title: 'Homepage Headliner Ad',
        dimensions: '1080×1920',
        width: 1080,
        height: 1920,
        aspectRatio: '9:16',
        format: 'Image',
        fileType: ['JPG', 'PNG'],
        maxFileSize: '350KB',
        maxFileSizeBytes: 350 * 1024,
        notes: 'Mobile Full-screen. Static full-screen mobile unit.'
      },
      {
        id: 'tw-premium-vid',
        title: 'Premium Video Ad',
        dimensions: '1920×1080',
        width: 1920,
        height: 1080,
        aspectRatio: '16:9',
        format: 'Video',
        fileType: ['MP4'],
        maxFileSize: 'N/A',
        settings: 'Encoding: H.264. bitrate 4000–10000kbps; 24–30fps; VAST with encodes at 1920×1080, 1280×720, 854×480, 640×360',
        notes: '≤30s (up to 60s for extra), unskippable.'
      },
      {
        id: 'tw-mid-feed',
        title: 'Mid-Feed Ad',
        dimensions: '1080×1920',
        width: 1080,
        height: 1920,
        aspectRatio: '9:16',
        format: 'Display',
        fileType: ['JPG', 'PNG'],
        maxFileSize: '250KB',
        maxFileSizeBytes: 250 * 1024,
        notes: 'Full screen mobile feed ad'
      },
      {
        id: 'tw-super-leader',
        title: 'Super Leaderboard Ad',
        dimensions: '728×90',
        width: 728,
        height: 90,
        aspectRatio: '8.09:1',
        format: 'Display',
        fileType: ['GIF', 'JPG', 'PNG'],
        maxFileSize: '50KB',
        maxFileSizeBytes: 50 * 1024,
        notes: 'Static or animated ≤15 s/3 loops'
      },
      {
        id: 'tw-med-rect',
        title: 'Medium Rectangle Ad',
        dimensions: '300×250',
        width: 300,
        height: 250,
        aspectRatio: '1.2:1',
        format: 'Display',
        fileType: ['JPG', 'PNG'],
        maxFileSize: 'N/A',
        notes: 'IAB medium rectangle; max 2 per page'
      }
    ]
  },
  {
    id: 'snapchat',
    name: 'Snapchat',
    description: 'Pioneered ephemeral content with self-destructing photo and video messages.',
    lastUpdated: '2025-06-17',
    specs: [
      {
        id: 'sc-image-ad',
        title: 'Image Ad',
        dimensions: '1080×1920',
        width: 1080,
        height: 1920,
        aspectRatio: '9:16',
        format: 'Image',
        fileType: ['JPG', 'PNG'],
        maxFileSize: '5MB',
        maxFileSizeBytes: 5 * 1024 * 1024,
        notes: 'The standard ad format. Keep key elements within the 175px top/bottom safe zone.'
      },
      {
        id: 'sc-video-ad',
        title: 'Video Ad',
        dimensions: '1080×1920',
        width: 1080,
        height: 1920,
        aspectRatio: '9:16',
        format: 'Video',
        fileType: ['MP4', 'MOV'],
        maxFileSize: '1GB',
        maxFileSizeBytes: 1 * 1024 * 1024 * 1024,
        notes: 'Audio: PCM or AAC codec. Keep key elements within safe zones.'
      },
      {
        id: 'sc-filter',
        title: 'Snapchat Filter Ad',
        dimensions: '1080×1920',
        width: 1080,
        height: 1920,
        aspectRatio: '9:16',
        format: 'Image',
        fileType: ['JPG', 'PNG'],
        maxFileSize: '5MB',
        maxFileSizeBytes: 5 * 1024 * 1024,
        notes: 'Under 300kb for static images. Buffer top and bottom to avoid UI elements.'
      },
      {
        id: 'sc-lens-img',
        title: 'Sponsored Lenses (Image)',
        dimensions: '1080×1920',
        width: 1080,
        height: 1920,
        aspectRatio: '9:16',
        format: 'Image',
        fileType: ['JPG', 'PNG'],
        maxFileSize: '5MB',
        maxFileSizeBytes: 5 * 1024 * 1024,
        notes: 'Include a visible brand logo. Max file size: 5MB (image), 1GB (video).'
      },
      {
        id: 'sc-lens-vid',
        title: 'Sponsored Lenses (Video)',
        dimensions: '1080×1920',
        width: 1080,
        height: 1920,
        aspectRatio: '9:16',
        format: 'Video',
        fileType: ['MP4', 'MOV'],
        maxFileSize: '1GB',
        maxFileSizeBytes: 1 * 1024 * 1024 * 1024,
        settings: 'Audio: PCM or AAC codec, 16 or 24 bit only, Audio target level should be -16 LUFS.',
        notes: 'Include a visible brand logo. Max file size: 5MB (image), 1GB (video).'
      }
    ]
  },
  {
    id: 'etsy',
    name: 'Etsy',
    description: 'A global online marketplace focused on handmade or vintage items and craft supplies.',
    lastUpdated: '2025-06-17',
    specs: [
      {
        id: 'etsy-shop-icon',
        title: 'Shop Icon',
        dimensions: '500×500',
        width: 500,
        height: 500,
        aspectRatio: '1:1',
        format: 'Image',
        fileType: ['JPG', 'PNG', 'GIF'],
        maxFileSize: '1MB',
        maxFileSizeBytes: 1024 * 1024,
        notes: 'Your shop\'s main logo, visible across the site.'
      },
      {
        id: 'etsy-listing',
        title: 'Listing Image',
        dimensions: '2700×2025',
        width: 2700,
        height: 2025,
        aspectRatio: '4:3',
        format: 'Image',
        fileType: ['JPG', 'PNG', 'GIF'],
        maxFileSize: '1MB',
        maxFileSizeBytes: 1024 * 1024,
        notes: 'Recommended. Use at least 2000px on the shortest side for zoom.'
      },
      {
        id: 'etsy-banner-big',
        title: 'Big Shop Banner',
        dimensions: '3360×840',
        width: 3360,
        height: 840,
        aspectRatio: '4:1',
        format: 'Image',
        fileType: ['JPG', 'PNG', 'GIF'],
        maxFileSize: '1MB',
        maxFileSizeBytes: 1024 * 1024,
        notes: 'The main, large header image for your shop\'s homepage.'
      },
      {
        id: 'etsy-profile',
        title: 'Profile Photo',
        dimensions: '400×400',
        width: 400,
        height: 400,
        aspectRatio: '1:1',
        format: 'Image',
        fileType: ['JPG', 'PNG', 'GIF'],
        maxFileSize: '1MB',
        maxFileSizeBytes: 1024 * 1024,
        notes: 'Represents you, the seller. Must be a clear headshot or logo.'
      },
      {
        id: 'etsy-banner-mini',
        title: 'Mini Shop Banner',
        dimensions: '1200×300',
        width: 1200,
        height: 300,
        aspectRatio: '4:1',
        format: 'Image',
        fileType: ['JPG', 'PNG', 'GIF'],
        maxFileSize: '1MB',
        maxFileSizeBytes: 1024 * 1024,
        notes: 'A smaller, more compact header option for your shop page.'
      },
      {
        id: 'etsy-receipt',
        title: 'Order Receipt Banner',
        dimensions: '760×100',
        width: 760,
        height: 100,
        aspectRatio: '19:2.5',
        format: 'Image',
        fileType: ['JPG', 'PNG', 'GIF'],
        maxFileSize: '1MB',
        maxFileSizeBytes: 1024 * 1024,
        notes: 'Appears at the top of your printable order confirmation receipts.'
      },
      {
        id: 'etsy-carousel',
        title: 'Carousel Banner',
        dimensions: '1200×300',
        width: 1200,
        height: 300,
        aspectRatio: '4:1',
        format: 'Image',
        fileType: ['JPG', 'PNG', 'GIF'],
        maxFileSize: '1MB',
        maxFileSizeBytes: 1024 * 1024,
        notes: 'Used to link to specific listings or sections from your homepage.'
      }
    ]
  },
  {
    id: 'reddit',
    name: 'Reddit',
    description: 'A vast network of communities, known as subreddits, where users can dive into their interests, hobbies, and passions.',
    lastUpdated: '2025-06-17',
    specs: [
      {
        id: 'reddit-profile-avatar',
        title: 'Profile Avatar',
        dimensions: '256×256',
        width: 256,
        height: 256,
        aspectRatio: '1:1',
        format: 'Image',
        fileType: ['JPG', 'PNG'],
        maxFileSize: '500KB',
        maxFileSizeBytes: 500 * 1024,
        notes: 'Appears on your profile and next to your posts and comments.'
      },
      {
        id: 'reddit-profile-banner',
        title: 'Profile Banner',
        dimensions: '1280×384',
        width: 1280,
        height: 384,
        aspectRatio: '10:3',
        format: 'Image',
        fileType: ['JPG', 'PNG'],
        maxFileSize: '500KB',
        maxFileSizeBytes: 500 * 1024,
        notes: 'The header image for your personal user profile page.'
      },
      {
        id: 'reddit-subreddit-icon',
        title: 'Subreddit Icon',
        dimensions: '256×256',
        width: 256,
        height: 256,
        aspectRatio: '1:1',
        format: 'Image',
        fileType: ['JPG', 'PNG'],
        maxFileSize: '500KB',
        maxFileSizeBytes: 500 * 1024,
        notes: 'The logo for a specific community (subreddit).'
      },
      {
        id: 'reddit-subreddit-banner',
        title: 'Subreddit Banner',
        dimensions: '4000×128',
        width: 4000,
        height: 128,
        aspectRatio: '125:4',
        format: 'Image',
        fileType: ['JPG', 'PNG'],
        maxFileSize: '5MB',
        maxFileSizeBytes: 5 * 1024 * 1024,
        notes: 'This is the medium size. Small (80px) and Large (192px) heights also available.'
      },
      {
        id: 'reddit-promoted-img',
        title: 'Promoted Post (Image)',
        dimensions: '1200×628',
        width: 1200,
        height: 628,
        aspectRatio: '1.91:1',
        format: 'Image',
        fileType: ['JPG', 'PNG'],
        maxFileSize: '3MB',
        maxFileSizeBytes: 3 * 1024 * 1024,
        notes: '1:1 ratio (1200×1200 px) is also highly recommended for ads.'
      },
      {
        id: 'reddit-promoted-carousel',
        title: 'Promoted Post (Carousel)',
        dimensions: '1200×1200',
        width: 1200,
        height: 1200,
        aspectRatio: '1:1',
        format: 'Image',
        fileType: ['JPG', 'PNG'],
        maxFileSize: '20MB',
        maxFileSizeBytes: 20 * 1024 * 1024,
        notes: 'Supports up to 6 cards. Each card can be an image or a video.'
      },
      {
        id: 'reddit-promoted-carousel-video',
        title: 'Promoted Post (Carousel)',
        dimensions: '1200×1200',
        width: 1200,
        height: 1200,
        aspectRatio: '1:1',
        format: 'Video',
        fileType: ['MP4', 'MOV'],
        maxFileSize: '1GB',
        maxFileSizeBytes: 1 * 1024 * 1024 * 1024,
        settings: 'Maximum frame rate: 30 fps.',
        notes: 'Supports up to 6 cards. Each card can be an image or a video.'
      },
      {
        id: 'reddit-promoted-video',
        title: 'Promoted Post (Video)',
        dimensions: '1080×1080',
        width: 1080,
        height: 1080,
        aspectRatio: '1:1',
        format: 'Video',
        fileType: ['MP4', 'MOV'],
        maxFileSize: '1GB',
        maxFileSizeBytes: 1 * 1024 * 1024 * 1024,
        settings: 'Maximum frame rate: 30 fps.',
        notes: 'Square (1:1) and vertical (4:5) videos perform best on mobile. Aspect ratio is 16:9, 1:1 or 4:5.'
      }
    ]
  },
  {
    id: 'spotify',
    name: 'Spotify',
    description: 'The world\'s leading audio streaming service, offering a vast library of music and podcasts.',
    lastUpdated: '2025-06-17',
    specs: [
      {
        id: 'spotify-profile',
        title: 'Profile Image (Avatar)',
        dimensions: '750×750',
        width: 750,
        height: 750,
        aspectRatio: '1:1',
        format: 'Image',
        fileType: ['JPG', 'PNG'],
        maxFileSize: '20MB',
        maxFileSizeBytes: 20 * 1024 * 1024,
        notes: 'Your primary artist or user image. Displayed as a circle. Minimum 300×300.'
      },
      {
        id: 'spotify-header',
        title: 'Header Image (Banner)',
        dimensions: '2660×1140',
        width: 2660,
        height: 1140,
        aspectRatio: '2.33:1',
        format: 'Image',
        fileType: ['JPG', 'PNG'],
        maxFileSize: '20MB',
        maxFileSizeBytes: 20 * 1024 * 1024,
        notes: 'For Artist Profiles. Keep key content centered to avoid cropping on different devices.'
      },
      {
        id: 'spotify-cover',
        title: 'Album/Podcast Cover',
        dimensions: '3000×3000',
        width: 3000,
        height: 3000,
        aspectRatio: '1:1',
        format: 'Image',
        fileType: ['JPG', 'PNG'],
        maxFileSize: '20MB',
        maxFileSizeBytes: 20 * 1024 * 1024,
        notes: 'Highest quality recommended. Minimum required size is 1400×1400 px.'
      },
      {
        id: 'spotify-playlist',
        title: 'Playlist Cover',
        dimensions: '600×600',
        width: 600,
        height: 600,
        aspectRatio: '1:1',
        format: 'Image',
        fileType: ['JPG', 'PNG'],
        maxFileSize: '20MB',
        maxFileSizeBytes: 20 * 1024 * 1024,
        notes: 'Recommended for custom playlists. Minimum is 300×300 px.'
      },
      {
        id: 'spotify-canvas',
        title: 'Canvas',
        dimensions: '1080×1920',
        width: 1080,
        height: 1920,
        aspectRatio: '9:16',
        format: 'Video',
        fileType: ['MP4', 'MOV'],
        maxFileSize: 'N/A',
        notes: 'Short (3-8 second) looping vertical video that accompanies a track.'
      }
    ]
  },
  {
    id: 'bluesky',
    name: 'Bluesky',
    description: 'A decentralized social networking platform that offers an open and customizable experience.',
    lastUpdated: '2025-06-20',
    specs: [
      {
        id: 'bs-profile',
        title: 'Profile Photo',
        dimensions: '400×400',
        width: 400,
        height: 400,
        aspectRatio: '1:1',
        format: 'Image',
        fileType: ['JPG', 'PNG'],
        maxFileSize: '2MB',
        maxFileSizeBytes: 2 * 1024 * 1024,
        notes: 'Displayed as a circle. Center key elements to avoid cropping.'
      },
      {
        id: 'bs-header',
        title: 'Header Photo',
        dimensions: '1500×500',
        width: 1500,
        height: 500,
        aspectRatio: '3:1',
        format: 'Image',
        fileType: ['JPG', 'PNG'],
        maxFileSize: '2MB',
        maxFileSizeBytes: 2 * 1024 * 1024,
        notes: 'Ensure key content is centered.'
      },
      {
        id: 'bs-post-sq',
        title: 'Post Image (Square)',
        dimensions: '1080×1080',
        width: 1080,
        height: 1080,
        aspectRatio: '1:1',
        format: 'Image',
        fileType: ['JPG', 'PNG'],
        maxFileSize: '2MB',
        maxFileSizeBytes: 2 * 1024 * 1024,
        notes: 'Ideal for balanced content. You can include up to 4 images per post.'
      }
    ]
  },
  {
    id: 'discord',
    name: 'Discord',
    description: 'A voice, video, and text chat app that brings people together around shared interests.',
    lastUpdated: '2025-06-20',
    specs: [
      {
        id: 'discord-profile',
        title: 'Profile Picture',
        dimensions: '512×512',
        width: 512,
        height: 512,
        aspectRatio: '1:1',
        format: 'Image',
        fileType: ['JPG', 'PNG', 'GIF'],
        maxFileSize: '8MB',
        maxFileSizeBytes: 8 * 1024 * 1024,
        notes: 'Recommended size. Minimum is 128x128 px. Displayed as a circle.'
      },
      {
        id: 'discord-server-icon',
        title: 'Server Icon',
        dimensions: '512×512',
        width: 512,
        height: 512,
        aspectRatio: '1:1',
        format: 'Image',
        fileType: ['JPG', 'PNG'],
        maxFileSize: '8MB',
        maxFileSizeBytes: 8 * 1024 * 1024,
        notes: 'The main logo for a server. Displayed as a circle.'
      },
      {
        id: 'discord-banner',
        title: 'Server Banner',
        dimensions: '960×540',
        width: 960,
        height: 540,
        aspectRatio: '16:9',
        format: 'Image',
        fileType: ['JPG', 'PNG'],
        maxFileSize: '8MB',
        maxFileSizeBytes: 8 * 1024 * 1024,
        notes: 'Requires a boosted server (Level 2+). Keep key info centered.'
      },
      {
        id: 'discord-invite',
        title: 'Server Invite Banner',
        dimensions: '1920×1080',
        width: 1920,
        height: 1080,
        aspectRatio: '16:9',
        format: 'Image',
        fileType: ['JPG', 'PNG'],
        maxFileSize: '8MB',
        maxFileSizeBytes: 8 * 1024 * 1024,
        notes: 'Splash image for invite links. Requires a boosted server (Level 3+).'
      },
      {
        id: 'discord-emoji',
        title: 'Custom Emoji',
        dimensions: '128×128',
        width: 128,
        height: 128,
        aspectRatio: '1:1',
        format: 'Image',
        fileType: ['JPG', 'PNG', 'GIF'],
        maxFileSize: '256KB',
        maxFileSizeBytes: 256 * 1024,
        notes: 'Recommended size for custom server emojis. File size must be under 256KB.'
      },
      {
        id: 'discord-sticker',
        title: 'Custom Stickers',
        dimensions: '320×320',
        width: 320,
        height: 320,
        aspectRatio: '1:1',
        format: 'Image',
        fileType: ['PNG', 'APNG'],
        maxFileSize: '512KB',
        maxFileSizeBytes: 512 * 1024,
        notes: 'Exact dimensions required. Use transparent background for best results.'
      },
      {
        id: 'discord-role-icon',
        title: 'Role Icon',
        dimensions: '64×64',
        width: 64,
        height: 64,
        aspectRatio: '1:1',
        format: 'Image',
        fileType: ['JPG', 'PNG'],
        maxFileSize: '256KB',
        maxFileSizeBytes: 256 * 1024,
        notes: 'Image displayed next to user\'s name. Requires a boosted server (Level 2+).'
      },
      {
        id: 'discord-embed',
        title: 'Embed Image',
        dimensions: '1200×630',
        width: 1200,
        height: 630,
        aspectRatio: '1.91:1',
        format: 'Image',
        fileType: ['JPG', 'PNG', 'GIF'],
        maxFileSize: '8MB',
        maxFileSizeBytes: 8 * 1024 * 1024,
        notes: 'Recommended Open Graph size for link previews. Discord generates these automatically.'
      }
    ]
  },
  {
    id: 'mastodon',
    name: 'Mastodon',
    description: 'A decentralized and open-source social network that allows users to create their own communities.',
    lastUpdated: '2025-06-21',
    specs: [
      {
        id: 'mastodon-avatar',
        title: 'Profile Avatar',
        dimensions: '400×400',
        width: 400,
        height: 400,
        aspectRatio: '1:1',
        format: 'Image',
        fileType: ['PNG', 'JPG', 'GIF'],
        maxFileSize: '16MB',
        maxFileSizeBytes: 16 * 1024 * 1024,
        notes: 'Displayed as a circle. Ensure focal point is centered.'
      },
      {
        id: 'mastodon-banner',
        title: 'Header (Profile Banner)',
        dimensions: '1500×500',
        width: 1500,
        height: 500,
        aspectRatio: '3:1',
        format: 'Image',
        fileType: ['PNG', 'JPG', 'GIF'],
        maxFileSize: '16MB',
        maxFileSizeBytes: 16 * 1024 * 1024,
        notes: 'The main banner image for your profile.'
      }
    ]
  }
];
