
import { 
  Layout, Smartphone, Video, TrendingUp, BarChart3, 
  MousePointer, Link, LineChart, Users, Zap, Activity, 
  Monitor, PieChart, Code, Search, Table, Split, CheckCircle, Calculator, Building2, Landmark, User, Bot, Sparkles, Eye, ExternalLink, FileText, QrCode, Link2, Shield
} from 'lucide-react';

export const TOOLS_CONFIG = [
  // AI & Trends
  {
    id: 'keyword-research',
    category: 'AI & Trends',
    title: 'AI Keyword Research (RAG)',
    description: 'Advanced GEO tool using simulated RAG to retrieve real-time trends, LLM citation data, and Reddit user intent.',
    icon: Sparkles,
    color: 'indigo',
    features: ['RAG Retrieval Simulation', 'LLM Visibility Score', 'Reddit Intent Mining']
  },
  {
    id: 'ai-search-visibility',
    category: 'AI & Trends',
    title: 'AI Search Visibility (GEO)',
    description: 'Track your brand\'s share of voice in AI responses (ChatGPT, Perplexity, Gemini). Analyze ranking prompts and competitor visibility.',
    icon: Eye,
    color: 'purple',
    features: ['Share of Voice', 'Competitor Benchmarking', 'Prompt Analysis']
  },
  {
    id: 'ai-prompt-generator',
    category: 'AI & Trends',
    title: 'AI Prompt Generator',
    description: 'Create high-quality AI prompts with proven frameworks like APE, RACE, CREATE, and SPARK. Generate professional prompts that deliver better results from ChatGPT, Claude, and other AI models.',
    icon: Bot,
    color: 'purple',
    features: ['APE Framework', 'RACE Framework', 'CREATE Framework', 'SPARK Framework', 'Multiple AI Types']
  },
  {
    id: 'ai-workflow-generator',
    category: 'AI & Trends',
    title: 'AI Workflow Generator',
    description: 'Generate AI workflows in JSON format for n8n, Make.com and other no-code platforms. Create perfect node connections with workflow diagrams.',
    icon: Zap,
    color: 'blue',
    features: ['n8n JSON Export', 'Make.com Integration', 'Node Connections', 'Workflow Diagrams', 'Copy & Paste Ready']
  },

  // Technical SEO
  {
    id: 'url-inspection',
    category: 'Technical SEO',
    title: 'URL Inspection Tool',
    description: 'Inspect any URL like Google Search Console. Check indexability, crawl status, Core Web Vitals, structured data, and get SEO recommendations.',
    icon: Search,
    color: 'blue',
    features: ['Index status check', 'Core Web Vitals', 'Structured data analysis', 'SEO recommendations']
  },
  {
    id: 'fetch-render',
    category: 'Technical SEO',
    title: 'Fetch & Render',
    description: 'Simulate how Googlebot fetches and renders your pages. Check status codes, blocked resources, and visual rendering issues.',
    icon: Monitor,
    color: 'blue',
    features: ['Fetch simulation', 'JavaScript rendering', 'Resource blocking check']
  },
  {
    id: 'rich-results',
    category: 'Technical SEO',
    title: 'Rich Results Test',
    description: 'Test your publicly accessible page to see which rich results can be generated by the structured data it contains.',
    icon: CheckCircle,
    color: 'emerald',
    features: ['Schema validation', 'Rich snippet preview', 'Error detection']
  },
  {
    id: 'pre-rendering',
    category: 'Technical SEO',
    title: 'Pre-rendering Testing Tool',
    description: 'Check what content is being served to different user agents to verify dynamic rendering or pre-rendering configuration.',
    icon: Split,
    color: 'indigo',
    features: ['User Agent comparison', 'Dynamic rendering detection', 'HTML snapshot analysis']
  },
  {
    id: 'schema-generator',
    category: 'Technical SEO',
    title: 'Schema Markup Generator',
    description: 'Generate JSON-LD structured data markup for articles, local businesses, products, FAQs, and more to improve SEO.',
    icon: Code,
    color: 'indigo',
    features: ['JSON-LD generation', 'Google Rich Results ready', 'Multiple schema types']
  },
  {
    id: 'serp-simulator',
    category: 'Technical SEO',
    title: 'Google SERP Simulator',
    description: 'Visualize how your website appears in Google search results. Optimize titles and meta descriptions for higher click-through rates.',
    icon: Search,
    color: 'blue',
    features: ['Snippet preview', 'Keyword highlighting', 'Mobile & Desktop view']
  },
  {
    id: 'sitemap-generator',
    category: 'Technical SEO',
    title: 'XML Sitemap Generator',
    description: 'Create professional XML sitemaps for your website. Add URLs, set priorities, change frequencies, and export as sitemap.xml.',
    icon: Code,
    color: 'green',
    features: ['XML generation', 'Bulk URL import', 'Priority & frequency settings', 'Instant export']
  },
  {
    id: 'bulk-url-opener',
    category: 'Technical SEO',
    title: 'Bulk URL Opener',
    description: 'Open multiple URLs at once in separate tabs for SEO audits, link verification, and batch checking.',
    icon: ExternalLink,
    color: 'teal',
    features: ['Bulk URL opening', 'Configurable delays', 'File upload support', 'URL validation']
  },
  {
    id: 'url-to-markdown',
    category: 'URL Converters',
    title: 'URL to Markdown',
    description: 'Convert webpages to clean Markdown format for documentation, notes, and content archiving.',
    icon: FileText,
    color: 'blue',
    features: ['Clean formatting', 'One-click download', 'Copy to clipboard']
  },
  {
    id: 'url-to-qrcode',
    category: 'URL Converters',
    title: 'URL to QR Code',
    description: 'Generate QR codes from URLs for easy sharing on marketing materials, business cards, and events.',
    icon: QrCode,
    color: 'purple',
    features: ['Customizable size', 'Instant generation', 'Download as PNG']
  },
  {
    id: 'url-encode-decode',
    category: 'URL Converters',
    title: 'URL Encode / Decode',
    description: 'Encode and decode text using URL, Base64, HTML entities, Unicode, Hex, Binary, and ROT13.',
    icon: Link2,
    color: 'indigo',
    features: ['8+ encoding formats', 'Batch processing', 'Copy & download']
  },
  {
    id: 'url-extractor',
    category: 'URL Converters',
    title: 'URL Extractor',
    description: 'Extract all URLs from websites instantly. Export as TXT or CSV for SEO audits and analysis.',
    icon: Link,
    color: 'green',
    features: ['Internal/External filtering', 'Export to TXT/CSV', 'Duplicate removal']
  },
  {
    id: 'mobile-index',
    category: 'Technical SEO',
    title: 'Mobile-First Index Tool',
    description: 'Test your site\'s readiness for Google\'s mobile-first index. Compare mobile vs desktop signals and get an AI readiness audit.',
    icon: Smartphone,
    color: 'blue',
    features: ['Mobile parity check', 'Technical signal audit', 'AI readiness report']
  },
  {
    id: 'mobile-friendly',
    category: 'Technical SEO',
    title: 'Mobile-Friendly Test (Bulk)',
    description: 'Bulk check pages for mobile-friendliness and usability errors. Analyze up to 50 URLs at once.',
    icon: Table,
    color: 'green',
    features: ['Bulk URL testing', 'Usability error detection', 'Exportable reports']
  },
  {
    id: 'amp-validator',
    category: 'Technical SEO',
    title: 'AMP Validator',
    description: 'Bulk validate URLs to check if they are valid Accelerated Mobile Pages (AMP). Checks linked AMPs and canonicals.',
    icon: Zap,
    color: 'orange',
    features: ['Bulk AMP validation', 'Linked AMP detection', 'User agent selection']
  },
  {
    id: 'sitemap-checker',
    category: 'Technical SEO',
    title: 'Sitemap Checker',
    description: 'Validate and analyze XML sitemaps for errors, broken links, and SEO issues.',
    icon: CheckCircle,
    color: 'green',
    features: ['XML validation', 'Broken link detection', 'SEO analysis']
  },
  {
    id: 'sitemap-split-merger',
    category: 'Technical SEO',
    title: 'Sitemap Split & Merger',
    description: 'Split large sitemaps into smaller ones or merge multiple sitemaps into a single file.',
    icon: Split,
    color: 'blue',
    features: ['Split large sitemaps', 'Merge multiple sitemaps', 'File size optimization']
  },
  {
    id: 'sitemap-urls-comparison',
    category: 'Technical SEO',
    title: 'Sitemap URLs Comparison',
    description: 'Compare two sitemaps to find added, removed, or changed URLs.',
    icon: BarChart3,
    color: 'purple',
    features: ['URL comparison', 'Change detection', 'Difference reports']
  },
  {
    id: 'sitemap-analytics',
    category: 'Technical SEO',
    title: 'Sitemap Analytics',
    description: 'Analyze sitemap data for insights on URL distribution, update frequencies, and optimization opportunities.',
    icon: BarChart3,
    color: 'indigo',
    features: ['URL distribution analysis', 'Update frequency tracking', 'Optimization recommendations']
  },
  {
    id: 'sitemap-robots-generator',
    category: 'Technical SEO',
    title: 'Sitemap Robots.txt Generator',
    description: 'Generate robots.txt files with sitemap references for proper crawler guidance.',
    icon: Code,
    color: 'teal',
    features: ['Robots.txt generation', 'Sitemap integration', 'Crawler directives']
  },
  {
    id: 'sitemap-frequency-analyzer',
    category: 'Technical SEO',
    title: 'Sitemap Frequency Analyzer',
    description: 'Analyze how often URLs in your sitemap are updated and suggest optimal change frequencies.',
    icon: Activity,
    color: 'orange',
    features: ['Update frequency analysis', 'Change detection', 'Optimization suggestions']
  },
  {
    id: 'website-url-extractor',
    category: 'Technical SEO',
    title: 'Website URL Extractor',
    description: 'Extract all URLs from a website for comprehensive link analysis and SEO audits.',
    icon: Link,
    color: 'green',
    features: ['Comprehensive URL extraction', 'Link analysis', 'SEO audit support']
  },

  // AI & Trends (continued)
  {
    id: 'ai-prompt-generator',
    category: 'AI & Trends',
    title: 'AI Prompt Generator',
    description: 'Generate effective prompts for AI tools and language models to get better results.',
    icon: Bot,
    color: 'purple',
    features: ['Prompt optimization', 'AI tool compatibility', 'Result improvement']
  },

  // Marketing Calculators
  {
    id: 'roi',
    category: 'Marketing Calculators',
    title: 'Campaign ROI Calculator',
    description: 'Calculate return on investment, profit, revenue per dollar (ROAS), and CPA for marketing campaigns.',
    icon: TrendingUp,
    color: 'emerald',
    features: ['Accurate ROI metrics', 'Cost per conversion analysis', 'Performance benchmarking']
  },
  {
    id: 'budget',
    category: 'Marketing Calculators',
    title: 'Ad Budget Planner',
    description: 'Plan your advertising budget based on revenue goals, target ROAS, and average CPC.',
    icon: BarChart3,
    color: 'blue',
    features: ['ROAS-based planning', 'Performance forecasting', 'Break-even analysis']
  },
  {
    id: 'landing-page',
    category: 'Marketing Calculators',
    title: 'Landing Page Impact Calculator',
    description: 'Calculate revenue impact of landing page optimization and conversion rate improvements.',
    icon: MousePointer,
    color: 'pink',
    features: ['Revenue impact calculation', 'CVR improvement analysis', 'Optimization ROI']
  },
  {
    id: 'utm',
    category: 'Marketing Calculators',
    title: 'UTM Tag Generator',
    description: 'Easily generate trackable URLs with UTM parameters to measure campaigns in analytics.',
    icon: Link,
    color: 'teal',
    features: ['Standard UTM parameters', 'Instant URL generation', 'One-click copy']
  },
  {
    id: 'clv',
    category: 'Marketing Calculators',
    title: 'CLV Calculator',
    description: 'Calculate Customer Lifetime Value (LTV) and determine sustainable Customer Acquisition Cost (CAC).',
    icon: Users,
    color: 'orange',
    features: ['Lifetime value formulas', 'CAC threshold analysis', 'Retention impact modeling']
  },
  {
    id: 'enterprise-seo',
    category: 'Marketing Calculators',
    title: 'Enterprise SEO ROI Calculator',
    description: 'Calculate ROI, payback period, and organic revenue growth for enterprise SEO campaigns.',
    icon: LineChart,
    color: 'purple',
    features: ['Traffic growth modeling', 'Net profit projection', 'Payback period analysis']
  },

  // Ad Mockups
  {
    id: 'google-mockup',
    category: 'Ad Mockups',
    title: 'Google Ad Mockup Generator',
    description: 'Create and visualize Google Search Ads exactly as they appear on search results pages.',
    icon: Layout,
    color: 'blue',
    features: ['Real-time search preview', 'Extension visualization', 'Desktop & Mobile views']
  },
  {
    id: 'facebook-mockup',
    category: 'Ad Mockups',
    title: 'Facebook Ad Mockup Generator',
    description: 'Create realistic Facebook Feed ad mockups in seconds. Visualize your copy, creative, and CTA buttons.',
    icon: Smartphone,
    color: 'blue',
    features: ['Feed ad preview', 'Social proof editing', 'Instant visualization']
  },
  {
    id: 'tiktok-mockup',
    category: 'Ad Mockups',
    title: 'TikTok Ad Preview Tool',
    description: 'Upload and visualize your creative assets in a simulated TikTok environment.',
    icon: Video,
    color: 'pink',
    features: ['Brand Takeover & In-Feed', 'Device frame simulation', 'Safe zone guides']
  },

  // Tax & Finance
  {
    id: 'vat-calculator',
    category: 'Tax & Finance',
    title: 'VAT Calculator',
    description: 'Calculate VAT amounts easily. Add VAT to net prices or remove VAT from gross figures. Supports custom rates.',
    icon: Calculator,
    color: 'blue',
    features: ['Add/Remove VAT modes', 'Custom rate support', 'Net/Gross breakdown']
  },
  {
    id: 'us-corporate-tax',
    category: 'Tax & Finance',
    title: 'US Corporate Tax Calculator',
    description: 'Estimate 2025 federal and state corporate income tax liabilities across all 50 states.',
    icon: Building2,
    color: 'blue',
    features: ['Federal + State breakdown', 'All 50 states data', 'Effective tax rate']
  },
  {
    id: 'aus-company-tax',
    category: 'Tax & Finance',
    title: 'Company Tax Calculator (AU)',
    description: 'Estimate Australian company tax liability. Supports Base Rate Entities (25%) and Standard Rate (30%).',
    icon: Landmark,
    color: 'teal',
    features: ['2023-2025 Tax Years', 'Base Rate Entity Toggle', 'Deductions Calculator']
  },
  {
    id: 'aus-simple-tax',
    category: 'Tax & Finance',
    title: 'Simple Tax Calculator (AU)',
    description: 'Calculate estimated tax on taxable income for Australian individuals. Includes 2024-2025 Stage 3 cuts.',
    icon: User,
    color: 'blue',
    features: ['Resident/Non-resident', 'Medicare Levy', 'Stage 3 Tax Cuts']
  },

  // SaaS & Business
  {
    id: 'saas',
    category: 'SaaS & Business',
    title: 'SaaS Pricing ROI Tool',
    description: 'Calculate ROI for upgrading software plans by analyzing time savings and efficiency gains.',
    icon: Zap,
    color: 'orange',
    features: ['Upgrade ROI calculation', 'Time savings quantification', 'Revenue impact projection']
  },
  {
    id: 'churn',
    category: 'SaaS & Business',
    title: 'Churn Impact Calculator',
    description: 'Quantify the cost of customer churn and the revenue impact of retention improvements.',
    icon: Activity,
    color: 'red',
    features: ['Revenue loss quantification', 'Retention improvement value', 'Long-term MRR projection']
  },
  {
    id: 'software-roi',
    category: 'SaaS & Business',
    title: 'Software ROI Calculator',
    description: 'Evaluate B2B software investments by comparing implementation costs against productivity savings.',
    icon: Monitor,
    color: 'indigo',
    features: ['Total cost of ownership', 'Productivity gain analysis', 'Multi-year projections']
  },
  {
    id: 'ebitda',
    category: 'SaaS & Business',
    title: 'EBITDA Calculator',
    description: 'Analyze operating performance by calculating Earnings Before Interest, Taxes, Depreciation, and Amortization.',
    icon: PieChart,
    color: 'blue',
    features: ['Net Income & Revenue methods', 'Multi-period trending', 'Margin benchmarking']
  },

  // Security & Utilities
  {
    id: 'password-generator',
    category: 'Security & Utilities',
    title: 'Password Generator',
    description: 'Generate cryptographically secure passwords with customizable options. Create strong, random passwords for enhanced security.',
    icon: Shield,
    color: 'green',
    features: ['Cryptographically secure', 'Customizable length', 'Character type options', 'Password strength meter', 'Copy & save']
  },
] as const;
