
import { 
  Layout, Smartphone, Video, TrendingUp, BarChart3, 
  MousePointer, Link, LineChart, Users, Zap, Activity, 
  Monitor, PieChart, Code, Search, Table, Split, CheckCircle, Calculator, Building2, Landmark, User
} from 'lucide-react';

export const TOOLS_CONFIG = [
  // SEO Tools (New Category)
  {
    id: 'fetch-render',
    category: 'SEO Tools',
    title: 'Fetch & Render',
    description: 'Simulate how Googlebot fetches and renders your pages. Check status codes, blocked resources, and visual rendering issues.',
    icon: Monitor,
    color: 'blue',
    features: ['Fetch simulation', 'JavaScript rendering', 'Resource blocking check']
  },
  {
    id: 'rich-results',
    category: 'SEO Tools',
    title: 'Rich Results Test',
    description: 'Test your publicly accessible page to see which rich results can be generated by the structured data it contains.',
    icon: CheckCircle,
    color: 'emerald',
    features: ['Schema validation', 'Rich snippet preview', 'Error detection']
  },
  {
    id: 'pre-rendering',
    category: 'SEO Tools',
    title: 'Pre-rendering Testing Tool',
    description: 'Check what content is being served to different user agents to verify dynamic rendering or pre-rendering configuration.',
    icon: Split,
    color: 'indigo',
    features: ['User Agent comparison', 'Dynamic rendering detection', 'HTML snapshot analysis']
  },
  {
    id: 'schema-generator',
    category: 'SEO Tools',
    title: 'Schema Markup Generator',
    description: 'Generate JSON-LD structured data markup for articles, local businesses, products, FAQs, and more to improve SEO.',
    icon: Code,
    color: 'indigo',
    features: ['JSON-LD generation', 'Google Rich Results ready', 'Multiple schema types']
  },
  {
    id: 'serp-simulator',
    category: 'SEO Tools',
    title: 'Google SERP Simulator',
    description: 'Visualize how your website appears in Google search results. Optimize titles and meta descriptions for higher click-through rates.',
    icon: Search,
    color: 'blue',
    features: ['Snippet preview', 'Keyword highlighting', 'Mobile & Desktop view']
  },
  {
    id: 'mobile-index',
    category: 'SEO Tools',
    title: 'Mobile-First Index Tool',
    description: 'Test your site\'s readiness for Google\'s mobile-first index. Compare mobile vs desktop signals and get an AI readiness audit.',
    icon: Smartphone,
    color: 'blue',
    features: ['Mobile parity check', 'Technical signal audit', 'AI readiness report']
  },
  {
    id: 'mobile-friendly',
    category: 'SEO Tools',
    title: 'Mobile-Friendly Test (Bulk)',
    description: 'Bulk check pages for mobile-friendliness and usability errors. Analyze up to 50 URLs at once.',
    icon: Table,
    color: 'green',
    features: ['Bulk URL testing', 'Usability error detection', 'Exportable reports']
  },
  {
    id: 'amp-validator',
    category: 'SEO Tools',
    title: 'AMP Validator',
    description: 'Bulk validate URLs to check if they are valid Accelerated Mobile Pages (AMP). Checks linked AMPs and canonicals.',
    icon: Zap,
    color: 'orange',
    features: ['Bulk AMP validation', 'Linked AMP detection', 'User agent selection']
  },
  {
    id: 'enterprise-seo',
    category: 'SEO Tools',
    title: 'Enterprise SEO ROI Calculator',
    description: 'Calculate ROI, payback period, and organic revenue growth for enterprise SEO campaigns.',
    icon: LineChart,
    color: 'purple',
    features: ['Traffic growth modeling', 'Net profit projection', 'Payback period analysis']
  },

  // Digital Marketing (Reclassified)
  {
    id: 'roi',
    category: 'Digital Marketing',
    title: 'Campaign ROI Calculator',
    description: 'Calculate return on investment, profit, revenue per dollar (ROAS), and CPA for marketing campaigns.',
    icon: TrendingUp,
    color: 'emerald',
    features: ['Accurate ROI metrics', 'Cost per conversion analysis', 'Performance benchmarking']
  },
  {
    id: 'budget',
    category: 'Digital Marketing',
    title: 'Ad Budget Planner',
    description: 'Plan your advertising budget based on revenue goals, target ROAS, and average CPC.',
    icon: BarChart3,
    color: 'blue',
    features: ['ROAS-based planning', 'Performance forecasting', 'Break-even analysis']
  },
  {
    id: 'landing-page',
    category: 'Digital Marketing',
    title: 'Landing Page Impact Calculator',
    description: 'Calculate revenue impact of landing page optimization and conversion rate improvements.',
    icon: MousePointer,
    color: 'pink',
    features: ['Revenue impact calculation', 'CVR improvement analysis', 'Optimization ROI']
  },
  {
    id: 'utm',
    category: 'Digital Marketing',
    title: 'UTM Tag Generator',
    description: 'Easily generate trackable URLs with UTM parameters to measure campaigns in analytics.',
    icon: Link,
    color: 'teal',
    features: ['Standard UTM parameters', 'Instant URL generation', 'One-click copy']
  },
  {
    id: 'clv',
    category: 'Digital Marketing',
    title: 'CLV Calculator',
    description: 'Calculate Customer Lifetime Value (LTV) and determine sustainable Customer Acquisition Cost (CAC).',
    icon: Users,
    color: 'orange',
    features: ['Lifetime value formulas', 'CAC threshold analysis', 'Retention impact modeling']
  },

  // Ad Mockups (New Category)
  {
    id: 'google-mockup',
    category: 'Ad Mockups',
    title: 'Google Ad Mockup Generator',
    description: 'Create and visualize Google Search Ads exactly as they appear on search results pages.',
    icon: Layout,
    color: 'blue',
    features: ['Real-time search preview', 'Extension visualization', 'Desktop & Mobile views']
  },
  {
    id: 'facebook-mockup',
    category: 'Ad Mockups',
    title: 'Facebook Ad Mockup Generator',
    description: 'Create realistic Facebook Feed ad mockups in seconds. Visualize your copy, creative, and CTA buttons.',
    icon: Smartphone,
    color: 'blue',
    features: ['Feed ad preview', 'Social proof editing', 'Instant visualization']
  },
  {
    id: 'tiktok-mockup',
    category: 'Ad Mockups',
    title: 'TikTok Ad Preview Tool',
    description: 'Upload and visualize your creative assets in a simulated TikTok environment.',
    icon: Video,
    color: 'pink',
    features: ['Brand Takeover & In-Feed', 'Device frame simulation', 'Safe zone guides']
  },

  // Business Tools (Existing)
  {
    id: 'vat-calculator',
    category: 'Business Tools',
    title: 'VAT Calculator',
    description: 'Calculate VAT amounts easily. Add VAT to net prices or remove VAT from gross figures. Supports custom rates.',
    icon: Calculator,
    color: 'blue',
    features: ['Add/Remove VAT modes', 'Custom rate support', 'Net/Gross breakdown']
  },
  {
    id: 'us-corporate-tax',
    category: 'Business Tools',
    title: 'US Corporate Tax Calculator',
    description: 'Estimate 2025 federal and state corporate income tax liabilities across all 50 states.',
    icon: Building2,
    color: 'blue',
    features: ['Federal + State breakdown', 'All 50 states data', 'Effective tax rate']
  },
  {
    id: 'aus-company-tax',
    category: 'Business Tools',
    title: 'Company Tax Calculator (AU)',
    description: 'Estimate Australian company tax liability. Supports Base Rate Entities (25%) and Standard Rate (30%).',
    icon: Landmark,
    color: 'teal',
    features: ['2023-2025 Tax Years', 'Base Rate Entity Toggle', 'Deductions Calculator']
  },
  {
    id: 'aus-simple-tax',
    category: 'Business Tools',
    title: 'Simple Tax Calculator (AU)',
    description: 'Calculate estimated tax on taxable income for Australian individuals. Includes 2024-2025 Stage 3 cuts.',
    icon: User,
    color: 'blue',
    features: ['Resident/Non-resident', 'Medicare Levy', 'Stage 3 Tax Cuts']
  },
  {
    id: 'saas',
    category: 'Business Tools',
    title: 'SaaS Pricing ROI Tool',
    description: 'Calculate ROI for upgrading software plans by analyzing time savings and efficiency gains.',
    icon: Zap,
    color: 'orange',
    features: ['Upgrade ROI calculation', 'Time savings quantification', 'Revenue impact projection']
  },
  {
    id: 'churn',
    category: 'Business Tools',
    title: 'Churn Impact Calculator',
    description: 'Quantify the cost of customer churn and the revenue impact of retention improvements.',
    icon: Activity,
    color: 'red',
    features: ['Revenue loss quantification', 'Retention improvement value', 'Long-term MRR projection']
  },
  {
    id: 'software-roi',
    category: 'Business Tools',
    title: 'Software ROI Calculator',
    description: 'Evaluate B2B software investments by comparing implementation costs against productivity savings.',
    icon: Monitor,
    color: 'indigo',
    features: ['Total cost of ownership', 'Productivity gain analysis', 'Multi-year projections']
  },
  {
    id: 'ebitda',
    category: 'Business Tools',
    title: 'EBITDA Calculator',
    description: 'Analyze operating performance by calculating Earnings Before Interest, Taxes, Depreciation, and Amortization.',
    icon: PieChart,
    color: 'blue',
    features: ['Net Income & Revenue methods', 'Multi-period trending', 'Margin benchmarking']
  },
] as const;
